/**
 * Jimaku.cc Japanese subtitle search and download service.
 * Supports searching entries, browsing files, and downloading Japanese subtitle tracks.
 */

import { parseSubtitleContent, parsedToSubtitleFetchResult } from "./subtitle-parsers";
import type { SubtitleFetchResult } from "~lib/types";

export interface JimakuEntry {
  id: number;
  name: string;
  japanese_name?: string;
  english_name?: string;
  anilist_id?: number;
  type?: string;
}

export interface JimakuFile {
  id: number;
  name: string;
  size?: number;
  download_count?: number;
  entry_id?: number;
}

const JIMAKU_BASE_URL = "https://jimaku.cc/api";

export class JimakuService {
  /** Search for anime/drama entries on Jimaku.cc */
  async searchEntries(query: string, apiKey: string): Promise<JimakuEntry[]> {
    if (!query.trim()) return [];

    const url = `${JIMAKU_BASE_URL}/entries/search?query=${encodeURIComponent(query.trim())}`;
    const headers: Record<string, string> = {
      "Accept": "application/json",
    };

    if (apiKey) {
      headers["Authorization"] = apiKey.trim();
    }

    const response = await fetch(url, { headers });
    if (!response.ok) {
      if (response.status === 401 || response.status === 403) {
        throw new Error("Jimaku.cc API key không hợp lệ hoặc đã hết hạn.");
      }
      throw new Error(`Jimaku search error: HTTP ${response.status}`);
    }

    const data = await response.json();
    if (Array.isArray(data)) {
      return data;
    }
    if (data && Array.isArray(data.data)) {
      return data.data;
    }
    return [];
  }

  /** Get list of subtitle files for a specific entry */
  async getEntryFiles(entryId: number, apiKey: string): Promise<JimakuFile[]> {
    const url = `${JIMAKU_BASE_URL}/entries/${entryId}/files`;
    const headers: Record<string, string> = {
      "Accept": "application/json",
    };

    if (apiKey) {
      headers["Authorization"] = apiKey.trim();
    }

    const response = await fetch(url, { headers });
    if (!response.ok) {
      throw new Error(`Jimaku get files error: HTTP ${response.status}`);
    }

    const data = await response.json();
    if (Array.isArray(data)) {
      return data;
    }
    if (data && Array.isArray(data.data)) {
      return data.data;
    }
    return [];
  }

  /** Download and parse a subtitle file into SubtitleFetchResult */
  async downloadSubtitle(file: JimakuFile, apiKey: string): Promise<SubtitleFetchResult> {
    const url = `${JIMAKU_BASE_URL}/files/${file.id}/download`;
    const headers: Record<string, string> = {};

    if (apiKey) {
      headers["Authorization"] = apiKey.trim();
    }

    const response = await fetch(url, { headers });
    if (!response.ok) {
      throw new Error(`Jimaku download error: HTTP ${response.status}`);
    }

    const text = await response.text();
    const parsed = parseSubtitleContent(text, file.name);

    if (parsed.segments.length === 0) {
      throw new Error("File phụ đề tải về không có đoạn thoại nào hợp lệ.");
    }

    return {
      videoId: `jimaku_${file.id}`,
      language: "ja",
      trackName: file.name,
      segments: parsed.segments,
      fullText: parsed.fullText,
      isAutoGenerated: false,
      source: "local_file",
    };
  }
}

export const jimakuService = new JimakuService();
