import type { SubtitleSegment, SubtitleWordTiming } from "~lib/types";

const SENTENCE_END_RE = /[。！？!?…][」』）】”’"]?$/u;
const NO_LEADING_SPACE_RE = /^[、。，．！？!?…：:；;」』）】]/u;
const CJK_EDGE_RE = /[\u3040-\u30ff\u3400-\u9fff]$/u;
const CJK_START_RE = /^[\u3040-\u30ff\u3400-\u9fff]/u;
const MAX_AUTO_CUE_CHARS = 48;
const MAX_MERGE_GAP_SECONDS = 0.45;
const SWITCH_GAP_SECONDS = 0.04;

function clamp(value: number, minimum: number, maximum: number): number {
  return Math.max(minimum, Math.min(maximum, value));
}

function wordEnd(word: SubtitleWordTiming): number {
  return word.start + Math.max(0, word.duration);
}

function nativeCueEnd(cue: SubtitleSegment): number {
  const timedWordEnd = cue.words?.reduce(
    (latest, word) => Math.max(latest, wordEnd(word)),
    cue.start
  ) ?? cue.start;
  return Math.max(
    cue.start + Math.max(0, cue.duration),
    timedWordEnd
  );
}

function joinCaptionText(left: string, right: string): string {
  const first = left.trim();
  const second = right.trim();
  if (!first) return second;
  if (!second) return first;
  if (second.startsWith(first)) return second;
  if (first.startsWith(second)) return first;
  const noSpace =
    CJK_EDGE_RE.test(first) ||
    CJK_START_RE.test(second) ||
    NO_LEADING_SPACE_RE.test(second);
  return `${first}${noSpace ? "" : " "}${second}`;
}

function mergeWords(
  left: SubtitleWordTiming[] | undefined,
  right: SubtitleWordTiming[] | undefined
): SubtitleWordTiming[] | undefined {
  if (!left?.length && !right?.length) return undefined;
  const seen = new Set<string>();
  return [...(left ?? []), ...(right ?? [])]
    .sort((a, b) => a.start - b.start)
    .filter((word) => {
      const key = `${word.start.toFixed(3)}|${word.text}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
}

function mergeCue(left: SubtitleSegment, right: SubtitleSegment): SubtitleSegment {
  const end = Math.max(nativeCueEnd(left), nativeCueEnd(right));
  return {
    text: joinCaptionText(left.text, right.text),
    start: Math.min(left.start, right.start),
    duration: Math.max(0, end - Math.min(left.start, right.start)),
    words: mergeWords(left.words, right.words),
    append: left.append || right.append,
  };
}

/**
 * Build stable reading cues without listening to audio.
 *
 * Manual tracks keep their author-provided segmentation. Auto captions only
 * merge adjacent fragments when they are separated by a short positive pause,
 * do not cross sentence punctuation and remain a readable size.
 */
export function buildSmartCues(
  segments: SubtitleSegment[],
  isAutoGenerated: boolean
): SubtitleSegment[] {
  const sorted = segments
    .filter((cue) => cue.text.trim() && Number.isFinite(cue.start))
    .map((cue) => ({
      ...cue,
      text: cue.text.replace(/\s+/g, " ").trim(),
      duration: Math.max(0, Number(cue.duration) || 0),
    }))
    .sort((a, b) => a.start - b.start);

  if (!isAutoGenerated) return sorted;

  const smart: SubtitleSegment[] = [];
  for (const cue of sorted) {
    const previous = smart[smart.length - 1];
    if (!previous) {
      smart.push(cue);
      continue;
    }

    const previousEnd = nativeCueEnd(previous);
    const gap = cue.start - previousEnd;
    const combined = joinCaptionText(previous.text, cue.text);
    const rollingReplacement =
      Math.abs(cue.start - previous.start) < 0.08 &&
      (cue.text.startsWith(previous.text) || previous.text.startsWith(cue.text));
    const shortSemanticGap =
      gap >= 0 &&
      gap <= MAX_MERGE_GAP_SECONDS &&
      !SENTENCE_END_RE.test(previous.text) &&
      combined.length <= MAX_AUTO_CUE_CHARS;
    const explicitAppend =
      cue.append &&
      gap <= 0.75 &&
      !SENTENCE_END_RE.test(previous.text) &&
      combined.length <= MAX_AUTO_CUE_CHARS;

    if (rollingReplacement || explicitAppend || shortSemanticGap) {
      smart[smart.length - 1] = mergeCue(previous, cue);
    } else {
      smart.push(cue);
    }
  }
  return smart;
}

/**
 * Calculate when one cue must disappear. A small visual tail prevents flicker,
 * but the cue always clears before the next cue begins.
 */
export function smartCueEnd(
  segments: SubtitleSegment[],
  index: number
): number {
  const cue = segments[index];
  if (!cue) return Number.NEGATIVE_INFINITY;
  const nextStart = segments[index + 1]?.start;
  let end = nativeCueEnd(cue);

  if (end <= cue.start) {
    if (Number.isFinite(nextStart)) {
      end = Math.max(cue.start + 0.1, nextStart! - 0.08);
    } else {
      end = cue.start + clamp(cue.text.length / 7, 0.8, 5);
    }
  }

  const tail = SENTENCE_END_RE.test(cue.text) ? 0.12 : 0.2;
  end += tail;
  if (Number.isFinite(nextStart)) {
    end = Math.min(end, Math.max(cue.start, nextStart! - SWITCH_GAP_SECONDS));
  }
  return end;
}

export function findSmartCue(
  segments: SubtitleSegment[],
  currentTime: number
): SubtitleSegment | null {
  let low = 0;
  let high = segments.length - 1;
  let bestIndex = -1;
  while (low <= high) {
    const middle = Math.floor((low + high) / 2);
    if (currentTime < segments[middle].start) {
      high = middle - 1;
    } else {
      bestIndex = middle;
      low = middle + 1;
    }
  }
  if (bestIndex < 0) return null;
  return currentTime <= smartCueEnd(segments, bestIndex)
    ? segments[bestIndex]
    : null;
}
