/**
 * In-Tab YouTube Subtitle & Caption Track Extractor (asbplayer style).
 * Runs in the YouTube tab context and communicates with the Main-World Bridge
 * to intercept network streams and switch player caption tracks.
 */

import type { CaptionTrack, SubtitleSegment, SubtitleFetchResult } from "~lib/types";
import { parseJson3Subtitles, parseXmlSubtitles, parseVttSubtitles, extractVideoId } from "./subtitle-fetcher";
import { parseSubtitleContent } from "./subtitle-parsers";
import { buildSmartCues } from "./smart-cue";
import { injectMainWorldBridge } from "./youtube-main-bridge-code";
import { fetchTranscriptPanelSubtitles } from "./youtube-transcript-dom";

export interface YouTubePlayerTrack {
  id: string;
  name: string;
  languageCode: string;
  baseUrl: string;
  vssId?: string;
  kind?: string;
  isAutoGenerated: boolean;
}

/** Get the current YouTube video title */
export function getYouTubeVideoTitle(): string {
  const moviePlayer = document.querySelector("#movie_player") as any;
  if (typeof moviePlayer?.getVideoData === "function") {
    const data = moviePlayer.getVideoData();
    if (data?.title) return data.title;
  }
  const h1 =
    document.querySelector("h1.ytd-watch-metadata yt-formatted-string") ||
    document.querySelector("#title h1 yt-formatted-string") ||
    document.querySelector("h1.title yt-formatted-string");
  if (h1?.textContent?.trim()) {
    return h1.textContent.trim();
  }
  return document.title.replace(/ - YouTube$/, "").trim();
}

/** Format display track name */
function formatTrackDisplayName(t: any): string {
  if (typeof t.name === "string" && t.name) return t.name;
  if (t.name?.simpleText) return t.name.simpleText;
  if (Array.isArray(t.name?.runs)) {
    const text = t.name.runs.map((r: any) => r.text || "").join("");
    if (text) return text;
  }
  if (typeof t.displayName === "string" && t.displayName) return t.displayName;
  if (typeof t.languageName === "string" && t.languageName) return t.languageName;
  if (typeof t.languageCode === "string" && t.languageCode) return t.languageCode;
  return "Unknown Track";
}

// Cache for tracks and captured timedtext
let bridgeTracksCache: YouTubePlayerTrack[] = [];
let bridgeVideoIdCache: string = "";
let lastCapturedTimedtext: { url: string; text: string; time: number } | null = null;
const capturedTimedtextMap = new Map<string, string>();

/** Register main-world bridge listener in the window */
if (typeof window !== "undefined") {
  injectMainWorldBridge();

  // Listen for stream-intercepted timedtext data
  window.addEventListener("hakkutsu:captured-timedtext", (e: any) => {
    const detail = e.detail;
    if (detail && detail.text) {
      lastCapturedTimedtext = {
        url: detail.url || "",
        text: detail.text,
        time: Date.now(),
      };
      if (detail.url) {
        capturedTimedtextMap.set(detail.url, detail.text);
      }
    }
  });

  // Listen for broadcasted tracks
  window.addEventListener("hakkutsu:bridge-tracks", (e: any) => {
    const detail = e.detail;
    const rawList = Array.isArray(detail) ? detail : detail?.tracks;
    const vid = detail?.videoId || "";

    if (vid) {
      bridgeVideoIdCache = vid;
    }

    if (Array.isArray(rawList) && rawList.length > 0) {
      const parsed: YouTubePlayerTrack[] = [];
      for (let i = 0; i < rawList.length; i++) {
        const t = rawList[i];
        const rawUrl = t.baseUrl || t.url || "";
        if (!rawUrl && !t.vssId) continue;
        const langCode = (t.languageCode || t.vssId || "")
          .toLowerCase()
          .replace(/^\./, "")
          .replace(/^a\./, "");
        const isAuto =
          t.kind === "asr" ||
          (t.vssId && (t.vssId.startsWith("a.") || t.vssId.startsWith("a:"))) ||
          !!t.isAutoGenerated;
        const name = formatTrackDisplayName(t);
        parsed.push({
          id: t.id || `yt_bridge_${i}_${langCode}`,
          name,
          languageCode: langCode,
          baseUrl: rawUrl,
          vssId: t.vssId,
          kind: t.kind,
          isAutoGenerated: isAuto,
        });
      }
      if (parsed.length > 0) {
        bridgeTracksCache = parsed;
      }
    }
  });
}

/** Request timedtext content directly from the Main World via custom event bridge */
export function fetchTimedtextViaMainWorld(
  url: string,
  timeoutMs: number = 4000
): Promise<string> {
  injectMainWorldBridge();

  return new Promise((resolve) => {
    if (typeof window === "undefined") {
      resolve("");
      return;
    }

    const requestId = `req_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`;
    let timer: number | null = null;

    const handler = (e: any) => {
      const detail = e.detail;
      if (detail && detail.requestId === requestId) {
        window.removeEventListener("hakkutsu:bridge-timedtext-response", handler);
        if (timer !== null) window.clearTimeout(timer);
        if (detail.success && detail.text) {
          resolve(detail.text);
        } else {
          resolve("");
        }
      }
    };

    window.addEventListener("hakkutsu:bridge-timedtext-response", handler);

    timer = window.setTimeout(() => {
      window.removeEventListener("hakkutsu:bridge-timedtext-response", handler);
      resolve("");
    }, timeoutMs);

    window.dispatchEvent(
      new CustomEvent("hakkutsu:fetch-timedtext-request", {
        detail: { requestId, url },
      })
    );
  });
}

/** Extract all available caption tracks directly from the YouTube player & bridge */
export function extractYouTubeTabTracks(): YouTubePlayerTrack[] {
  injectMainWorldBridge();

  const tracks: YouTubePlayerTrack[] = [];
  const seenIds = new Set<string>();

  // Helper to extract video ID
  let currentVideoId = "";
  const moviePlayer = document.querySelector("#movie_player") as any;
  if (typeof moviePlayer?.getVideoData === "function") {
    currentVideoId = moviePlayer.getVideoData()?.video_id || "";
  }
  if (!currentVideoId && typeof window !== "undefined") {
    currentVideoId = extractVideoId(window.location.href) || "";
  }

  // 1. Primary source: Main-World Bridge tracks cache
  if (
    bridgeTracksCache.length > 0 &&
    (!bridgeVideoIdCache || !currentVideoId || bridgeVideoIdCache === currentVideoId)
  ) {
    for (const t of bridgeTracksCache) {
      if (t.baseUrl && !seenIds.has(t.id)) {
        seenIds.add(t.id);
        tracks.push(t);
      }
    }
  }

  // 2. Try getPlayerResponse or ytInitialPlayerResponse in current context
  const pr =
    (typeof moviePlayer?.getPlayerResponse === "function"
      ? moviePlayer.getPlayerResponse()
      : null) ||
    (window as any).ytInitialPlayerResponse ||
    (document.querySelector("ytd-watch-flexy") as any)?.data?.playerResponse;

  const captionTracks =
    pr?.captions?.playerCaptionsTracklistRenderer?.captionTracks ||
    pr?.captions?.playerCaptionsRenderer?.captionTracks;

  if (Array.isArray(captionTracks) && captionTracks.length > 0) {
    for (let i = 0; i < captionTracks.length; i++) {
      const t = captionTracks[i];
      let rawUrl = t.baseUrl || t.url || "";
      const langCode = (t.languageCode || t.vssId || "")
        .toLowerCase()
        .replace(/^\./, "")
        .replace(/^a\./, "");
      const isAuto =
        t.kind === "asr" ||
        (t.vssId && (t.vssId.startsWith("a.") || t.vssId.startsWith("a:")));
      const name = formatTrackDisplayName(t);

      if (!rawUrl && currentVideoId && langCode) {
        rawUrl = `https://www.youtube.com/api/timedtext?v=${currentVideoId}&lang=${langCode}&fmt=json3`;
      }
      if (!rawUrl) continue;

      const trackId = `yt_tab_${i}_${langCode}`;
      if (!seenIds.has(trackId)) {
        seenIds.add(trackId);
        tracks.push({
          id: trackId,
          name,
          languageCode: langCode,
          baseUrl: rawUrl,
          vssId: t.vssId,
          kind: t.kind,
          isAutoGenerated: !!isAuto,
        });
      }
    }
  }

  // 3. Request fresh bridge tracks for the next render
  if (typeof window !== "undefined") {
    try {
      window.dispatchEvent(new CustomEvent("hakkutsu:request-bridge-tracks"));
    } catch {}
  }

  // 4. Auto-translate Japanese Generation (asbplayer mechanism)
  // If no native Japanese track is found, but other tracks exist, generate YouTube auto-translated Japanese track (&tlang=ja)
  const hasJaTrack = tracks.some(
    (t) =>
      t.languageCode === "ja" ||
      t.languageCode.startsWith("ja") ||
      t.name.includes("日本語") ||
      t.name.includes("Japanese")
  );

  if (!hasJaTrack && tracks.length > 0) {
    const baseTrack =
      tracks.find((t) => !t.isAutoGenerated && t.baseUrl) ||
      tracks.find((t) => t.baseUrl) ||
      tracks[0];
    if (baseTrack && baseTrack.baseUrl) {
      let autoJaUrl = baseTrack.baseUrl;
      if (autoJaUrl.includes("tlang=")) {
        autoJaUrl = autoJaUrl.replace(/tlang=[^&]+/, "tlang=ja");
      } else {
        autoJaUrl = autoJaUrl.includes("?") ? `${autoJaUrl}&tlang=ja` : `${autoJaUrl}?tlang=ja`;
      }

      tracks.unshift({
        id: `yt_auto_translate_ja`,
        name: `日本語 (${baseTrack.name} - Auto Translate)`,
        languageCode: "ja",
        baseUrl: autoJaUrl,
        vssId: ".ja",
        kind: "asr",
        isAutoGenerated: true,
      });
    }
  }

  return tracks;
}

/** Fetch timedtext content for a specific track directly in the tab */
export async function fetchYouTubeTrackInTab(
  track: YouTubePlayerTrack,
  videoId: string
): Promise<SubtitleFetchResult> {
  injectMainWorldBridge();

  // Helper to parse response text regardless of content-type
  const parseResponseText = (text: string): SubtitleSegment[] => {
    if (!text || !text.trim()) return [];
    try {
      const json = JSON.parse(text);
      const segs = parseJson3Subtitles(json);
      if (segs.length > 0) return segs;
    } catch {}

    if (text.includes("-->")) {
      const segs = parseVttSubtitles(text);
      if (segs.length > 0) return segs;
    }

    const xmlSegs = parseXmlSubtitles(text);
    if (xmlSegs.length > 0) return xmlSegs;

    try {
      const universal = parseSubtitleContent(text);
      if (universal.segments.length > 0) return universal.segments;
    } catch {}

    return [];
  };

  // Helper for background fetch (uses chrome.scripting in MAIN World)
  const doBackgroundFetch = async (fetchUrl: string): Promise<string> => {
    try {
      const bgResp: any = await chrome.runtime.sendMessage({
        type: "FETCH_TIMEDTEXT_URL",
        payload: { url: fetchUrl },
      });
      if (bgResp?.payload?.success && bgResp?.payload?.text) {
        return bgResp.payload.text;
      }
    } catch (bgErr) {
      console.warn("Hakkutsu: Background timedtext fetch failed", bgErr);
    }
    return "";
  };

  // Helper for in-tab direct fetch fallback
  const doDirectFetch = async (fetchUrl: string): Promise<string> => {
    try {
      const res = await window.fetch(fetchUrl, { credentials: "include" });
      if (res.ok) {
        return await res.text();
      }
    } catch (err) {
      console.warn("Hakkutsu: In-tab direct fetch failed", err);
    }
    return "";
  };

  // Normalize target URL (unescape &amp; and ensure absolute https)
  let rawUrl = (track.baseUrl || "").replace(/&amp;/g, "&").trim();
  if (!rawUrl && videoId && track.languageCode) {
    rawUrl = `https://www.youtube.com/api/timedtext?v=${videoId}&lang=${track.languageCode}&fmt=json3`;
  }
  let targetUrl = rawUrl.startsWith("//")
    ? `https:${rawUrl}`
    : rawUrl.startsWith("http")
      ? rawUrl
      : `https://www.youtube.com${rawUrl}`;

  let segments: SubtitleSegment[] = [];
  const startTime = Date.now();

  // ── 1. asbplayer Strategy: Switch player caption track via Main World API ───
  if (typeof window !== "undefined") {
    try {
      window.dispatchEvent(
        new CustomEvent("hakkutsu:set-player-track", {
          detail: {
            track: {
              languageCode: track.languageCode,
              vssId: track.vssId,
              name: track.name,
              kind: track.kind,
            },
          },
        })
      );
    } catch {}
  }

  // ── 2. Check if Interceptor caught the timedtext response ───────────────────
  const waitForCapturedText = async (maxWaitMs: number): Promise<string> => {
    const deadline = Date.now() + maxWaitMs;
    while (Date.now() < deadline) {
      if (lastCapturedTimedtext && lastCapturedTimedtext.time >= startTime) {
        return lastCapturedTimedtext.text;
      }
      if (targetUrl && capturedTimedtextMap.has(targetUrl)) {
        return capturedTimedtextMap.get(targetUrl)!;
      }
      await new Promise((r) => setTimeout(r, 80));
    }
    return "";
  };

  let captured = await waitForCapturedText(600);
  if (captured) {
    segments = parseResponseText(captured);
  }

  // ── 3. Authenticated Background Scripting Fetch (MAIN World) ────────────────
  if (segments.length === 0 && targetUrl) {
    let text = await doBackgroundFetch(targetUrl);
    segments = parseResponseText(text);
  }

  // ── 4. Try with fmt=json3 parameter ─────────────────────────────────────────
  if (segments.length === 0 && targetUrl) {
    const jsonUrl = targetUrl.includes("fmt=")
      ? targetUrl.replace(/fmt=[^&]+/, "fmt=json3")
      : targetUrl.includes("?")
        ? `${targetUrl}&fmt=json3`
        : `${targetUrl}?fmt=json3`;
    let text = await doBackgroundFetch(jsonUrl);
    if (!text) text = await fetchTimedtextViaMainWorld(jsonUrl, 1500);
    segments = parseResponseText(text);
  }

  // ── 5. Try with fmt=srv3 (XML format 3) ─────────────────────────────────────
  if (segments.length === 0 && targetUrl) {
    const srv3Url = targetUrl.includes("fmt=")
      ? targetUrl.replace(/fmt=[^&]+/, "fmt=srv3")
      : targetUrl.includes("?")
        ? `${targetUrl}&fmt=srv3`
        : `${targetUrl}?fmt=srv3`;
    let text = await doBackgroundFetch(srv3Url);
    if (!text) text = await fetchTimedtextViaMainWorld(srv3Url, 1500);
    segments = parseResponseText(text);
  }

  // ── 6. Try with fmt=vtt (WebVTT) ────────────────────────────────────────────
  if (segments.length === 0 && targetUrl) {
    const vttUrl = targetUrl.includes("fmt=")
      ? targetUrl.replace(/fmt=[^&]+/, "fmt=vtt")
      : targetUrl.includes("?")
        ? `${targetUrl}&fmt=vtt`
        : `${targetUrl}?fmt=vtt`;
    let text = await doBackgroundFetch(vttUrl);
    if (!text) text = await fetchTimedtextViaMainWorld(vttUrl, 1500);
    segments = parseResponseText(text);
  }

  // ── 7. Try clean direct timedtext URL ───────────────────────────────────────
  if (segments.length === 0 && videoId && track.languageCode) {
    const cleanTimedtextUrl = `https://www.youtube.com/api/timedtext?v=${videoId}&lang=${track.languageCode}&fmt=json3`;
    if (cleanTimedtextUrl !== targetUrl) {
      let text = await doBackgroundFetch(cleanTimedtextUrl);
      if (!text) text = await fetchTimedtextViaMainWorld(cleanTimedtextUrl, 1500);
      segments = parseResponseText(text);
    }
  }

  // ── 8. In-Tab Direct Fetch Fallback ─────────────────────────────────────────
  if (segments.length === 0 && targetUrl) {
    const text = await doDirectFetch(targetUrl);
    segments = parseResponseText(text);
  }

  // ── 9. Transcript Panel DOM Scraper Fallback ────────────────────────────────
  if (segments.length === 0) {
    try {
      const transcriptResult = await fetchTranscriptPanelSubtitles(videoId);
      if (transcriptResult && transcriptResult.segments.length > 0) {
        return transcriptResult;
      }
    } catch (transcriptErr) {
      console.warn("Hakkutsu: Transcript panel fallback failed", transcriptErr);
    }
  }

  if (segments.length === 0) {
    throw new Error(`Không thể đọc được nội dung phụ đề cho track "${track.name}".`);
  }

  const smartSegments = buildSmartCues(segments, track.isAutoGenerated);

  return {
    videoId,
    language: track.languageCode,
    trackName: track.name,
    segments: smartSegments,
    fullText: smartSegments.map((s) => s.text).join(" "),
    isAutoGenerated: track.isAutoGenerated,
    source: "player",
  };
}
