/**
 * In-Tab YouTube Subtitle & Caption Track Extractor.
 * Runs directly in the YouTube tab context to bypass CORS/PO-token restrictions.
 */

import type { CaptionTrack, SubtitleSegment, SubtitleFetchResult } from "~lib/types";
import { parseJson3Subtitles, parseXmlSubtitles, parseVttSubtitles } from "./subtitle-fetcher";
import { buildSmartCues } from "./smart-cue";

export interface YouTubePlayerTrack {
  id: string;
  name: string;
  languageCode: string;
  baseUrl: string;
  vssId?: string;
  kind?: string;
  isAutoGenerated: boolean;
}

/** Get the current YouTube video title */
export function getYouTubeVideoTitle(): string {
  const moviePlayer = document.querySelector("#movie_player") as any;
  if (typeof moviePlayer?.getVideoData === "function") {
    const data = moviePlayer.getVideoData();
    if (data?.title) return data.title;
  }
  const h1 = document.querySelector("h1.ytd-watch-metadata yt-formatted-string") ||
    document.querySelector("#title h1 yt-formatted-string");
  if (h1?.textContent?.trim()) {
    return h1.textContent.trim();
  }
  return document.title.replace(/ - YouTube$/, "").trim();
}

/** Format display track name */
function formatTrackDisplayName(t: any): string {
  if (typeof t.name === "string" && t.name) return t.name;
  if (t.name?.simpleText) return t.name.simpleText;
  if (Array.isArray(t.name?.runs)) {
    const text = t.name.runs.map((r: any) => r.text || "").join("");
    if (text) return text;
  }
  if (typeof t.displayName === "string" && t.displayName) return t.displayName;
  if (typeof t.languageName === "string" && t.languageName) return t.languageName;
  if (typeof t.languageCode === "string" && t.languageCode) return t.languageCode;
  return "Unknown Track";
}

/** Extract all available caption tracks directly from the YouTube player */
export function extractYouTubeTabTracks(): YouTubePlayerTrack[] {
  const tracks: YouTubePlayerTrack[] = [];
  const moviePlayer = document.querySelector("#movie_player") as any;

  // 1. Try movie_player.getOption("captions", "tracklist")
  if (typeof moviePlayer?.getOption === "function") {
    try {
      const list = moviePlayer.getOption("captions", "tracklist");
      if (Array.isArray(list) && list.length > 0) {
        for (let i = 0; i < list.length; i++) {
          const t = list[i];
          const rawUrl = t.baseUrl || t.url || "";
          if (!rawUrl && !t.vssId) continue;

          const langCode = (t.languageCode || t.vssId || "").toLowerCase().replace(/^\./, "").replace(/^a\./, "");
          const isAuto = t.kind === "asr" || (t.vssId && (t.vssId.startsWith("a.") || t.vssId.startsWith("a:")));
          const name = formatTrackDisplayName(t);

          tracks.push({
            id: `yt_track_${i}_${langCode}`,
            name,
            languageCode: langCode,
            baseUrl: rawUrl,
            vssId: t.vssId,
            kind: t.kind,
            isAutoGenerated: isAuto,
          });
        }
      }
    } catch (e) {
      console.warn("Hakkutsu: Error reading movie_player caption tracklist", e);
    }
  }

  // 2. Fallback: inspect ytInitialPlayerResponse or player response
  if (tracks.length === 0) {
    const pr =
      (typeof moviePlayer?.getPlayerResponse === "function" ? moviePlayer.getPlayerResponse() : null) ||
      (window as any).ytInitialPlayerResponse ||
      (document.querySelector("ytd-watch-flexy") as any)?.data?.playerResponse;

    const captionTracks = pr?.captions?.playerCaptionsTracklistRenderer?.captionTracks ||
      pr?.captions?.playerCaptionsRenderer?.captionTracks;

    if (Array.isArray(captionTracks)) {
      for (let i = 0; i < captionTracks.length; i++) {
        const t = captionTracks[i];
        const rawUrl = t.baseUrl || t.url || "";
        if (!rawUrl) continue;

        const langCode = (t.languageCode || t.vssId || "").toLowerCase().replace(/^\./, "").replace(/^a\./, "");
        const isAuto = t.kind === "asr" || (t.vssId && (t.vssId.startsWith("a.") || t.vssId.startsWith("a:")));
        const name = formatTrackDisplayName(t);

        tracks.push({
          id: `yt_initial_${i}_${langCode}`,
          name,
          languageCode: langCode,
          baseUrl: rawUrl,
          vssId: t.vssId,
          kind: t.kind,
          isAutoGenerated: isAuto,
        });
      }
    }
  }

  // 3. Fallback: inspect script tags for captionTracks JSON if still empty
  if (tracks.length === 0) {
    try {
      const scripts = document.querySelectorAll("script");
      for (let i = 0; i < scripts.length; i++) {
        const text = scripts[i].textContent || "";
        if (text.includes("captionTracks")) {
          const match = text.match(/["']captionTracks["']\s*:\s*(\[[^\]]+\])/);
          if (match) {
            const parsed = JSON.parse(match[1]);
            if (Array.isArray(parsed)) {
              for (let j = 0; j < parsed.length; j++) {
                const t = parsed[j];
                const rawUrl = t.baseUrl || t.url || "";
                if (!rawUrl) continue;

                const langCode = (t.languageCode || t.vssId || "").toLowerCase().replace(/^\./, "").replace(/^a\./, "");
                const isAuto = t.kind === "asr" || (t.vssId && (t.vssId.startsWith("a.") || t.vssId.startsWith("a:")));
                const name = formatTrackDisplayName(t);

                tracks.push({
                  id: `yt_script_${j}_${langCode}`,
                  name,
                  languageCode: langCode,
                  baseUrl: rawUrl,
                  vssId: t.vssId,
                  kind: t.kind,
                  isAutoGenerated: isAuto,
                });
              }
            }
          }
        }
        if (tracks.length > 0) break;
      }
    } catch (err) {
      console.warn("Hakkutsu: Script parsing for captionTracks failed", err);
    }
  }

  // 4. Auto-translate Japanese Generation (asbplayer mechanism)
  // If no native Japanese track is found, but other tracks exist, generate YouTube auto-translated Japanese track (&tlang=ja)
  const hasJaTrack = tracks.some(
    (t) =>
      t.languageCode === "ja" ||
      t.languageCode.startsWith("ja") ||
      t.name.includes("日本語") ||
      t.name.includes("Japanese")
  );

  if (!hasJaTrack && tracks.length > 0) {
    const baseTrack = tracks.find((t) => !t.isAutoGenerated) || tracks[0];
    if (baseTrack && baseTrack.baseUrl) {
      let autoJaUrl = baseTrack.baseUrl;
      if (autoJaUrl.includes("tlang=")) {
        autoJaUrl = autoJaUrl.replace(/tlang=[^&]+/, "tlang=ja");
      } else {
        autoJaUrl = `${autoJaUrl}&tlang=ja`;
      }

      tracks.unshift({
        id: `yt_auto_translate_ja`,
        name: `日本語 (${baseTrack.name} - Auto Translate)`,
        languageCode: "ja",
        baseUrl: autoJaUrl,
        vssId: ".ja",
        kind: "asr",
        isAutoGenerated: true,
      });
    }
  }

  return tracks;
}

/** Fetch timedtext content for a specific track directly in the tab */
export async function fetchYouTubeTrackInTab(
  track: YouTubePlayerTrack,
  videoId: string
): Promise<SubtitleFetchResult> {
  if (!track.baseUrl) {
    throw new Error(`Track "${track.name}" không có URL timedtext hợp lệ.`);
  }

  // Normalize target URL (unescape &amp; and ensure absolute https)
  let rawUrl = track.baseUrl.replace(/&amp;/g, "&").trim();
  let targetUrl = rawUrl.startsWith("//")
    ? `https:${rawUrl}`
    : rawUrl.startsWith("http")
      ? rawUrl
      : `https://www.youtube.com${rawUrl}`;

  let segments: SubtitleSegment[] = [];

  // Helper to parse response text regardless of content-type
  const parseResponseText = (text: string): SubtitleSegment[] => {
    if (!text || !text.trim()) return [];
    try {
      const json = JSON.parse(text);
      const segs = parseJson3Subtitles(json);
      if (segs.length > 0) return segs;
    } catch {}

    if (text.includes("-->")) {
      const segs = parseVttSubtitles(text);
      if (segs.length > 0) return segs;
    }

    const xmlSegs = parseXmlSubtitles(text);
    if (xmlSegs.length > 0) return xmlSegs;

    return [];
  };

  const doFetch = async (fetchUrl: string): Promise<string> => {
    try {
      const res = await window.fetch(fetchUrl, { credentials: "include" });
      if (res.ok) {
        return await res.text();
      }
    } catch (err) {
      console.warn("Hakkutsu: Direct fetch error", err);
    }
    return "";
  };

  // 1. First attempt: fetch targetUrl EXACTLY as provided by YouTube (Preserves server signature)
  let text = await doFetch(targetUrl);
  segments = parseResponseText(text);

  // 2. Second attempt: if 0 segments, try appending fmt=json3 if not already present
  if (segments.length === 0 && !targetUrl.includes("fmt=")) {
    const jsonUrl = targetUrl.includes("?") ? `${targetUrl}&fmt=json3` : `${targetUrl}?fmt=json3`;
    text = await doFetch(jsonUrl);
    segments = parseResponseText(text);
  }

  // 3. Third attempt: try appending fmt=vtt if still 0 segments
  if (segments.length === 0 && !targetUrl.includes("fmt=")) {
    const vttUrl = targetUrl.includes("?") ? `${targetUrl}&fmt=vtt` : `${targetUrl}?fmt=vtt`;
    text = await doFetch(vttUrl);
    segments = parseResponseText(text);
  }

  // 4. Background service worker fallback
  if (segments.length === 0) {
    try {
      const bgResp: any = await chrome.runtime.sendMessage({
        type: "FETCH_TIMEDTEXT_URL",
        payload: { url: targetUrl },
      });
      if (bgResp?.payload?.success && bgResp?.payload?.text) {
        segments = parseResponseText(bgResp.payload.text);
      }
    } catch (bgErr) {
      console.warn("Hakkutsu: Background timedtext fetch fallback failed", bgErr);
    }
  }

  if (segments.length === 0) {
    throw new Error(`Không thể đọc được phụ đề cho track "${track.name}".`);
  }

  const smartSegments = buildSmartCues(segments, track.isAutoGenerated);

  return {
    videoId,
    language: track.languageCode,
    trackName: track.name,
    segments: smartSegments,
    fullText: smartSegments.map((s) => s.text).join(" "),
    isAutoGenerated: track.isAutoGenerated,
    source: "player",
  };
}
