/**
 * In-Tab YouTube Subtitle & Caption Track Extractor.
 * Runs directly in the YouTube tab context to bypass CORS/PO-token restrictions.
 */

import type { CaptionTrack, SubtitleSegment, SubtitleFetchResult } from "~lib/types";
import { parseJson3Subtitles, parseXmlSubtitles, parseVttSubtitles } from "./subtitle-fetcher";
import { buildSmartCues } from "./smart-cue";

export interface YouTubePlayerTrack {
  id: string;
  name: string;
  languageCode: string;
  baseUrl: string;
  vssId?: string;
  kind?: string;
  isAutoGenerated: boolean;
}

/** Get the current YouTube video title */
export function getYouTubeVideoTitle(): string {
  const moviePlayer = document.querySelector("#movie_player") as any;
  if (typeof moviePlayer?.getVideoData === "function") {
    const data = moviePlayer.getVideoData();
    if (data?.title) return data.title;
  }
  const h1 = document.querySelector("h1.ytd-watch-metadata yt-formatted-string") ||
    document.querySelector("#title h1 yt-formatted-string");
  if (h1?.textContent?.trim()) {
    return h1.textContent.trim();
  }
  return document.title.replace(/ - YouTube$/, "").trim();
}

/** Format display track name */
function formatTrackDisplayName(t: any): string {
  if (typeof t.name === "string" && t.name) return t.name;
  if (t.name?.simpleText) return t.name.simpleText;
  if (Array.isArray(t.name?.runs)) {
    const text = t.name.runs.map((r: any) => r.text || "").join("");
    if (text) return text;
  }
  if (typeof t.displayName === "string" && t.displayName) return t.displayName;
  if (typeof t.languageName === "string" && t.languageName) return t.languageName;
  if (typeof t.languageCode === "string" && t.languageCode) return t.languageCode;
  return "Unknown Track";
}

/** Extract all available caption tracks directly from the YouTube player */
export function extractYouTubeTabTracks(): YouTubePlayerTrack[] {
  const tracks: YouTubePlayerTrack[] = [];
  const moviePlayer = document.querySelector("#movie_player") as any;

  // 1. Try movie_player.getOption("captions", "tracklist")
  if (typeof moviePlayer?.getOption === "function") {
    try {
      const list = moviePlayer.getOption("captions", "tracklist");
      if (Array.isArray(list) && list.length > 0) {
        for (let i = 0; i < list.length; i++) {
          const t = list[i];
          const rawUrl = t.baseUrl || t.url || "";
          if (!rawUrl && !t.vssId) continue;

          const langCode = (t.languageCode || t.vssId || "").toLowerCase().replace(/^\./, "").replace(/^a\./, "");
          const isAuto = t.kind === "asr" || (t.vssId && (t.vssId.startsWith("a.") || t.vssId.startsWith("a:")));
          const name = formatTrackDisplayName(t);

          tracks.push({
            id: `yt_track_${i}_${langCode}`,
            name,
            languageCode: langCode,
            baseUrl: rawUrl,
            vssId: t.vssId,
            kind: t.kind,
            isAutoGenerated: isAuto,
          });
        }
      }
    } catch (e) {
      console.warn("Hakkutsu: Error reading movie_player caption tracklist", e);
    }
  }

  // 2. Fallback: inspect ytInitialPlayerResponse or player response
  if (tracks.length === 0) {
    const pr =
      (typeof moviePlayer?.getPlayerResponse === "function" ? moviePlayer.getPlayerResponse() : null) ||
      (window as any).ytInitialPlayerResponse;

    const captionTracks = pr?.captions?.playerCaptionsTracklistRenderer?.captionTracks ||
      pr?.captions?.playerCaptionsRenderer?.captionTracks;

    if (Array.isArray(captionTracks)) {
      for (let i = 0; i < captionTracks.length; i++) {
        const t = captionTracks[i];
        const rawUrl = t.baseUrl || t.url || "";
        if (!rawUrl) continue;

        const langCode = (t.languageCode || t.vssId || "").toLowerCase().replace(/^\./, "").replace(/^a\./, "");
        const isAuto = t.kind === "asr" || (t.vssId && (t.vssId.startsWith("a.") || t.vssId.startsWith("a:")));
        const name = formatTrackDisplayName(t);

        tracks.push({
          id: `yt_initial_${i}_${langCode}`,
          name,
          languageCode: langCode,
          baseUrl: rawUrl,
          vssId: t.vssId,
          kind: t.kind,
          isAutoGenerated: isAuto,
        });
      }
    }
  }

  return tracks;
}

/** Fetch timedtext content for a specific track directly in the tab */
export async function fetchYouTubeTrackInTab(
  track: YouTubePlayerTrack,
  videoId: string
): Promise<SubtitleFetchResult> {
  if (!track.baseUrl) {
    throw new Error(`Track "${track.name}" không có URL timedtext hợp lệ.`);
  }

  // Ensure absolute HTTPS URL
  let targetUrl = track.baseUrl.startsWith("//")
    ? `https:${track.baseUrl}`
    : track.baseUrl.startsWith("http")
      ? track.baseUrl
      : `https://www.youtube.com${track.baseUrl}`;

  const urlObj = new URL(targetUrl);
  // Request json3 format
  urlObj.searchParams.set("fmt", "json3");

  let segments: SubtitleSegment[] = [];

  try {
    const res = await window.fetch(urlObj.toString(), {
      credentials: "include",
    });

    if (res.ok) {
      const text = await res.text();
      try {
        const json = JSON.parse(text);
        segments = parseJson3Subtitles(json);
      } catch {
        // Not JSON, try XML or VTT
        if (text.includes("-->")) {
          segments = parseVttSubtitles(text);
        } else {
          segments = parseXmlSubtitles(text);
        }
      }
    }
  } catch (err) {
    console.warn("Hakkutsu: In-tab json3 fetch failed, trying standard XML", err);
  }

  // Fallback to XML
  if (segments.length === 0) {
    urlObj.searchParams.delete("fmt");
    const res = await window.fetch(urlObj.toString(), {
      credentials: "include",
    });
    if (res.ok) {
      const text = await res.text();
      segments = parseXmlSubtitles(text);
    }
  }

  if (segments.length === 0) {
    throw new Error(`Không thể đọc được phụ đề cho track "${track.name}".`);
  }

  const smartSegments = buildSmartCues(segments, track.isAutoGenerated);

  return {
    videoId,
    language: track.languageCode,
    trackName: track.name,
    segments: smartSegments,
    fullText: smartSegments.map((s) => s.text).join(" "),
    isAutoGenerated: track.isAutoGenerated,
    source: "player",
  };
}
