// Anki Types

/**
 * Anki-related type definitions.
 */

export interface AnkiNote {
  deckName: string;
  modelName: string;
  fields: Record<string, string>;
  options?: {
    allowDuplicate?: boolean;
  };
  tags?: string[];
}

export interface AnkiConnectRequest {
  action: string;
  version: number;
  params?: Record<string, unknown>;
}

export interface AnkiConnectResponse {
  result: unknown;
  error: string | null;
}

export interface AnkiDeck {
  name: string;
}

export interface AnkiModel {
  name: string;
  fields: string[];
}

export interface AnkiExportData {
  word: string;
  reading: string;
  wordFurigana?: string;
  meaning: string;
  vietnameseSound?: string;
  sentence: string;
  sentenceFurigana?: string;
  sentenceReading?: string;
  sentenceMeaning?: string;
  jlptLevel: string;
  pos: string;
  screenshot?: string;
  imageUrl?: string;
  sourceUrl?: string;
  audio?: string;
  sentenceAudio?: string;
}


// API Types

/**
 * API response types matching the FastAPI backend schemas.
 */

// ── Grammar ─────────────────────────────────────────────────────────────────

export interface GrammarPattern {
  pattern: string;
  meaning: string;
  explanation: string;
  jlpt_level: string | null;
}

// ── Token Analysis ──────────────────────────────────────────────────────────

export interface TokenReading {
  hiragana: string;
  romaji: string;
}

export interface DictionaryEntry {
  dictionary?: string;
  glosses: string[];
  pos: string[];
  field: string | null;
  misc: string[];
}

export interface TokenAnalysis {
  surface: string;
  dictionary_form: string;
  reading: TokenReading;
  pos: string;
  pos_detail: string[];
  is_japanese: boolean;
  jlpt_level: string | null;
  frequency_rank: number | null;
  definitions: DictionaryEntry[];
  vietnamese_sound?: string;
  srs_state?: string | null;
  grammar_note_vi?: string;
  imageUrl?: string;
  components?: Array<{
    surface: string;
    lemma: string;
    reading: string;
    part_of_speech: string;
  }>;
}

export interface AnalyzeRequest {
  text: string;
  include_definitions?: boolean;
  include_examples?: boolean;
  user_id?: string;
}

export interface AnalyzeResponse {
  text: string;
  tokens: TokenAnalysis[];
  sentence_reading: string;
  token_count: number;
  difficulty_score: number | null;
  difficulty_label: string | null;
  grammar_patterns?: GrammarPattern[];
}

export interface PhraseAnalyzeResponse extends AnalyzeResponse {
  translation: string;
}

export interface WebTranslateItem {
  index: number;
  source: string;
  translation: string;
  tokens: TokenAnalysis[];
}

export interface WebTranslateResponse {
  source_language?: string;
  target_language?: string;
  items?: WebTranslateItem[];
  translations?: Array<{ id: number; text: string }>;
}

// ── Subtitles ───────────────────────────────────────────────────────────────

export interface SubtitleSegment {
  text: string;
  start: number;
  duration: number;
  words?: SubtitleWordTiming[];
  append?: boolean;
}

export interface SubtitleWordTiming {
  text: string;
  start: number;
  duration: number;
}

export interface SubtitleRequest {
  video_url: string;
  language?: string;
}

export interface SubtitleResponse {
  video_id: string;
  language: string;
  track_name?: string;
  is_auto_generated?: boolean;
  segments: SubtitleSegment[];
  full_text: string;
}

// ── YouTube Caption Tracks ──────────────────────────────────────────────────

export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name: string;
  kind: string;
  isAutoGenerated: boolean;
}

export interface SubtitleFetchResult {
  videoId: string;
  language: string;
  segments: SubtitleSegment[];
  fullText: string;
  trackName: string;
  isAutoGenerated: boolean;
  source?: "player" | "transcript_panel" | "backend" | "local_file" | "text_track";
  offset?: number;
}

// ── Common ──────────────────────────────────────────────────────────────────

export interface ApiError {
  error: string;
  detail: string | null;
  code: string;
}

export interface HealthResponse {
  status: string;
  service: string;
  version: string;
}


// Extension Types

/**
 * Extension-specific type definitions.
 */

export type ExtensionView = "translate" | "srs";

export interface ExtensionSettings {
  targetLanguage: "vi" | "en" | "zh" | "ja" | "ko";
  showHanViet: boolean;
  ankiEnabled: boolean;
  ankiDeck: string;
  ankiModel: string;
  ankiImageField: string;
  ankiFieldMap: Record<string, string>;
  includeImages: boolean;
  autoDetect: boolean;
  showFurigana: boolean;
  showJlptColors: boolean;
  hoverModifierKey: "alt" | "ctrl" | "shift" | "meta" | "none";
  theme: "dark" | "light" | "auto";
  fontSize: "small" | "medium" | "large";
  srsEnabled: boolean;
  textAnalysisEnabled: boolean;
  subtitlesEnabled: boolean;
  subtitlesFontSize: number;
  subtitlesSecondaryEnabled: boolean;
  subtitlesAutoPause: boolean;
  subtitlesOffset: number;
  netflixBtnPosition?: { x: number; y: number } | null;
}

export const DEFAULT_SETTINGS: ExtensionSettings = {
  targetLanguage: "vi",
  showHanViet: true,
  ankiEnabled: true,
  ankiDeck: "Hakkutsu",
  ankiModel: "Hakkutsu Japanese",
  ankiImageField: "Image",
  ankiFieldMap: {},
  includeImages: true,
  autoDetect: true,
  showFurigana: true,
  showJlptColors: true,
  hoverModifierKey: "alt",
  theme: "dark",
  fontSize: "medium",
  srsEnabled: true,
  textAnalysisEnabled: true,
  subtitlesEnabled: true,
  subtitlesFontSize: 26,
  subtitlesSecondaryEnabled: true,
  subtitlesAutoPause: false,
  subtitlesOffset: 0,
  netflixBtnPosition: null,
};

export interface VocabularyEntry {
  id: string;
  word: string;
  reading: string;
  meaning: string;
  jlptLevel: string | null;
  context: string;
  sourceUrl: string;
  addedAt: number;
  exported: boolean;
  imageUrl?: string;
}

export interface SelectionEvent {
  text: string;
  context: string;
  x: number;
  y: number;
  sourceUrl: string;
}

/** Message types for communication between content scripts and background */
export type MessageType =
  | "ANALYZE_TEXT"
  | "ANALYZE_RESULT"
  | "ANALYZE_JAVI"
  | "ANALYZE_PHRASE"
  | "ANALYZE_PHRASE_RESULT"
  | "EXPORT_ANKI"
  | "ANKI_RESULT"
  | "CHECK_ANKI"
  | "ANKI_STATUS"
  | "GET_SETTINGS"
  | "UPDATE_SETTINGS"
  | "TEXT_SELECTED"
  | "ADD_SRS_CARD"
  | "SRS_RESULT"
  | "CHECK_CARD_EXISTS"
  | "CARD_EXISTS_RESULT"
  | "REMOVE_SRS_CARD"
  | "REMOVE_SRS_CARD_RESULT"
  | "OPEN_APP"
  | "OPEN_APP_RESULT"
  | "TRANSLATE_TEXT"
  | "TRANSLATE_RESULT"
  | "FETCH_TTS_AUDIO"
  | "TTS_AUDIO_RESULT"
  | "START_OCR_FLOW"
  | "START_OCR_FLOW_RESULT"
  | "CAPTURE_SCREENSHOT"
  | "SCREENSHOT_RESULT"
  | "FETCH_IMAGE"
  | "FETCH_IMAGE_RESULT"
  | "FETCH_TIMEDTEXT_URL"
  | "FETCH_TIMEDTEXT_URL_RESULT"
  | "OCR_IMAGE"
  | "OCR_RESULT"
  | "IGNORED"
  | "ERROR";

export interface ExtensionMessage {
  type: MessageType;
  payload?: unknown;
}


// Manga Studio Types

export interface Manga {
  id: string;
  title: string;
  author: string;
  description: string;
  thumbnail: string | null;
  tags: string;
  created_at: string;
  updated_at: string;
}

export interface Chapter {
  id: string;
  chapter_number: string;
  title: string;
  status: string;
  created_at: string;
  updated_at: string;
}

export interface Page {
  id: string;
  page_number: number;
  original_image_path: string;
  clean_image_path: string | null;
  mask_preview_path: string | null;
  bubble_preview_path: string | null;
  bubble_analysis_path: string | null;
  width: number;
  height: number;
  status: string;
  created_at: string;
  updated_at: string;
}

export interface TextBlock {
  id: string;
  x: number;
  y: number;
  width: number;
  height: number;
  source_x: number | null;
  source_y: number | null;
  source_width: number | null;
  source_height: number | null;
  original_text: string;
  ai_translation: string;
  final_translation: string;
  font_family: string;
  font_size: number;
  color: string;
  text_align: string;
  text_offset_y: number;
  placement_anchor_x: number | null;
  placement_anchor_y: number | null;
  rotation: number;
  ocr_confidence: number | null;
  ocr_provider: string | null;
  created_at: string;
  updated_at: string;
}
