import type { SubtitleSegment } from "~/features/subtitles/shared/types";
import { parseYouTubeJson3, parseYouTubeTimedTextXml } from "~/features/subtitles/shared/subtitle-parsers";
import { buildSmartCues } from "~/features/subtitles/shared/smart-cue";

let requestSequence = 0;

export function requestPageCaptionContent(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const requestId = `caption-${Date.now()}-${++requestSequence}`;
    const finish = (text?: string, error?: string) => {
      clearTimeout(timer);
      document.removeEventListener("hakkutsu:youtube-caption-content", listener);
      if (error) reject(new Error(error));
      else resolve(text || "");
    };
    const listener = (event: Event) => {
      const result = (event as CustomEvent).detail;
      if (result?.requestId !== requestId) return;
      finish(typeof result.text === "string" ? result.text : "", result.error);
    };
    const timer = setTimeout(() => finish(undefined, "YouTube caption request timed out"), 9000);
    document.addEventListener("hakkutsu:youtube-caption-content", listener);
    document.dispatchEvent(new CustomEvent("hakkutsu:request-youtube-caption-content", { detail: { requestId, url } }));
  });
}

export async function loadYouTubeCaptionTrack(track: {
  url?: string; name: string; isAutoGenerated?: boolean;
}): Promise<SubtitleSegment[]> {
  if (!track.url) throw new Error("Missing subtitle track URL");
  const urls = [track.url];
  const jsonUrl = new URL(track.url, window.location.href);
  jsonUrl.searchParams.set("fmt", "json3");
  if (jsonUrl.toString() !== track.url) urls.push(jsonUrl.toString());
  let lastError = "The server returned no readable captions";
  const parse = (text: string): SubtitleSegment[] => {
    if (!text.trim()) return [];
    const segments = text.trim().startsWith("{") ? parseYouTubeJson3(text) : parseYouTubeTimedTextXml(text);
    return buildSmartCues(segments, Boolean(track.isAutoGenerated));
  };
  for (const url of urls) {
    const transports = [
      async () => {
        const controller = new AbortController();
        const timer = setTimeout(() => controller.abort(), 8000);
        try {
          const response = await fetch(url, { credentials: "include", signal: controller.signal });
          if (!response.ok) throw new Error(`HTTP ${response.status}`);
          return await response.text();
        } finally { clearTimeout(timer); }
      },
      () => requestPageCaptionContent(url),
      async () => {
        const response = await chrome.runtime.sendMessage({ type: "FETCH_TIMEDTEXT_URL", payload: { url } });
        if (!response?.payload?.success) throw new Error(response?.payload?.error || "Caption request failed");
        return String(response.payload.text || "");
      },
    ];
    for (const transport of transports) {
      try {
        const segments = parse(await transport());
        if (segments.length > 0) return segments;
      } catch (error) { lastError = error instanceof Error ? error.message : String(error); }
    }
  }
  throw new Error(`Could not load ${track.name}: ${lastError}`);
}
