/**
 * API response types matching the FastAPI backend schemas.
 */

// ── Grammar ─────────────────────────────────────────────────────────────────

export interface GrammarPattern {
  pattern: string;
  meaning: string;
  explanation: string;
  jlpt_level: string | null;
}

// ── Token Analysis ──────────────────────────────────────────────────────────

export interface TokenReading {
  hiragana: string;
  romaji: string;
}

export interface DictionaryEntry {
  dictionary?: string;
  glosses: string[];
  pos: string[];
  field: string | null;
  misc: string[];
}

export interface TokenAnalysis {
  surface: string;
  dictionary_form: string;
  reading: TokenReading;
  pos: string;
  pos_detail: string[];
  is_japanese: boolean;
  jlpt_level: string | null;
  frequency_rank: number | null;
  definitions: DictionaryEntry[];
  srs_state?: string | null;
  grammar_note_vi?: string;
  components?: Array<{
    surface: string;
    lemma: string;
    reading: string;
    part_of_speech: string;
  }>;
}

export interface AnalyzeRequest {
  text: string;
  include_definitions?: boolean;
  include_examples?: boolean;
  user_id?: string;
}

export interface AnalyzeResponse {
  text: string;
  tokens: TokenAnalysis[];
  sentence_reading: string;
  token_count: number;
  difficulty_score: number | null;
  difficulty_label: string | null;
  grammar_patterns?: GrammarPattern[];
}

export interface PhraseAnalyzeResponse extends AnalyzeResponse {
  translation: string;
}

export interface WebTranslateItem {
  index: number;
  source: string;
  translation: string;
  tokens: TokenAnalysis[];
}

export interface WebTranslateResponse {
  source_language: "ja";
  target_language: "vi";
  items: WebTranslateItem[];
}

// ── Subtitles ───────────────────────────────────────────────────────────────

export interface SubtitleSegment {
  text: string;
  start: number;
  duration: number;
  words?: SubtitleWordTiming[];
  append?: boolean;
}

export interface SubtitleWordTiming {
  text: string;
  start: number;
  duration: number;
}

export interface SubtitleRequest {
  video_url: string;
  language?: string;
}

export interface SubtitleResponse {
  video_id: string;
  language: string;
  track_name?: string;
  is_auto_generated?: boolean;
  segments: SubtitleSegment[];
  full_text: string;
}

// ── OCR ─────────────────────────────────────────────────────────────────────

export interface OcrRegion {
  text: string;
  confidence: number;
  bbox: number[] | null;
}

export interface OcrRequest {
  image_data: string;
  language?: string;
}

export interface OcrResponse {
  full_text: string;
  regions: OcrRegion[];
  language: string;
}

// ── YouTube Caption Tracks ──────────────────────────────────────────────────

export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name: string;
  kind: string;
  isAutoGenerated: boolean;
}

export interface SubtitleFetchResult {
  videoId: string;
  language: string;
  segments: SubtitleSegment[];
  fullText: string;
  trackName: string;
  isAutoGenerated: boolean;
  source?: "player" | "transcript_panel" | "backend";
}

// ── Common ──────────────────────────────────────────────────────────────────

export interface ApiError {
  error: string;
  detail: string | null;
  code: string;
}

export interface HealthResponse {
  status: string;
  service: string;
  version: string;
}
