/**
 * YouTube subtitle extraction service.
 *
 * Extracts subtitle data from YouTube's internal player response.
 * Designed to run in the background service worker where CORS
 * restrictions don't apply due to host_permissions.
 *
 * Strategy:
 * 1. Fetch the YouTube watch page HTML
 * 2. Extract `ytInitialPlayerResponse` from the page source
 * 3. Parse caption tracks from the player response
 * 4. Fetch the selected track's subtitle data in JSON3 format
 * 5. Parse into our SubtitleSegment[] format
 */

import type {
  CaptionTrack,
  SubtitleSegment,
  SubtitleFetchResult,
} from "~types";

/** Extract video ID from various YouTube URL formats */
function extractVideoId(url: string): string | null {
  const patterns = [
    /[?&]v=([a-zA-Z0-9_-]{11})/,
    /youtu\.be\/([a-zA-Z0-9_-]{11})/,
    /youtube\.com\/embed\/([a-zA-Z0-9_-]{11})/,
  ];

  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) return match[1];
  }

  return null;
}

/** Parse ytInitialPlayerResponse from YouTube page HTML */
function parsePlayerResponse(html: string): Record<string, unknown> | null {
  // YouTube embeds player data in a script tag as:
  //   var ytInitialPlayerResponse = {...};
  // We use a regex that matches until the next variable declaration or end of script
  const patterns = [
    /ytInitialPlayerResponse\s*=\s*(\{.+?\})\s*;\s*(?:var\s|<\/script>)/s,
    /\["ytInitialPlayerResponse"\]\s*=\s*(\{.+?\})\s*;\s*(?:var\s|<\/script>)/s
  ];

  for (const pattern of patterns) {
    const match = html.match(pattern);
    if (match) {
      try {
        return JSON.parse(match[1]);
      } catch (e) {
        console.warn("Hakkutsu: Failed to parse ytInitialPlayerResponse regex match", e);
      }
    }
  }

  // Fallback: manual string extraction
  const marker = "ytInitialPlayerResponse = ";
  const startIdx = html.indexOf(marker);
  if (startIdx !== -1) {
    const jsonStart = startIdx + marker.length;
    const scriptEnd = html.indexOf("</script>", jsonStart);
    if (scriptEnd !== -1) {
      let candidate = html.substring(jsonStart, scriptEnd).trim();
      const lastBrace = candidate.lastIndexOf("};");
      if (lastBrace !== -1) {
        candidate = candidate.substring(0, lastBrace + 1);
        try {
          return JSON.parse(candidate);
        } catch (e) {
          console.warn("Hakkutsu: Failed to parse ytInitialPlayerResponse fallback match", e);
        }
      }
    }
  }

  return null;
}

/** Extract caption tracks from the player response */
function extractCaptionTracks(
  playerResponse: Record<string, unknown>
): CaptionTrack[] {
  const captions = (playerResponse as Record<string, Record<string, unknown>>)
    ?.captions;
  if (!captions) return [];

  const renderer = (
    captions as Record<string, Record<string, unknown>>
  )?.playerCaptionsTracklistRenderer;
  if (!renderer) return [];

  const captionTracks = (renderer as Record<string, unknown[]>)?.captionTracks;
  if (!Array.isArray(captionTracks)) return [];

  return captionTracks.map(
    (track: Record<string, unknown>): CaptionTrack => ({
      baseUrl: (track.baseUrl as string) || "",
      languageCode: (track.languageCode as string) || "",
      name:
        ((track.name as Record<string, string>)?.simpleText as string) || "",
      kind: (track.kind as string) || "",
      isAutoGenerated: (track.kind as string) === "asr" || typeof track.vssId === "string" && track.vssId.startsWith("a."),
    })
  );
}

/** Represents a single event in YouTube's JSON3 subtitle format */
interface Json3Event {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: Array<{ utf8?: string }>;
}

/** Parse YouTube JSON3 subtitle format into SubtitleSegment[] */
function parseJson3Subtitles(json3Data: Record<string, unknown>): SubtitleSegment[] {
  const events = (json3Data as { events?: Json3Event[] }).events;
  if (!Array.isArray(events)) return [];

  const segments: SubtitleSegment[] = [];

  for (const event of events) {
    // Skip events without segments (e.g. format/style events)
    if (!event.segs || !event.tStartMs) continue;

    const text = event.segs
      .map((seg) => seg.utf8 || "")
      .join("")
      .replace(/\n/g, " ")
      .trim();

    if (!text) continue;

    segments.push({
      text,
      start: event.tStartMs / 1000,
      duration: (event.dDurationMs || 0) / 1000,
    });
  }

  return segments;
}

/**
 * Find the best Japanese caption track from available tracks.
 * Prefers manually-created tracks over auto-generated ones.
 */
function findJapaneseTrack(
  tracks: CaptionTrack[],
  language: string = "ja"
): CaptionTrack | null {
  // Prefer manual subtitles
  const manual = tracks.find(
    (t) => t.languageCode === language && !t.isAutoGenerated
  );
  if (manual) return manual;

  // Fall back to auto-generated
  const auto = tracks.find(
    (t) => t.languageCode === language && t.isAutoGenerated
  );
  if (auto) return auto;

  // Translation fallback
  const englishAuto = tracks.find(
    (t) => t.languageCode === "en" && t.isAutoGenerated
  );
  if (englishAuto) return englishAuto;

  return null;
}

export async function fetchSubtitlesFromPlayerResponse(
  playerResponse: Record<string, unknown>,
  videoId: string,
  language: string = "ja"
): Promise<SubtitleFetchResult> {
  // Step 3: Get caption tracks
  const tracks = extractCaptionTracks(playerResponse);
  if (tracks.length === 0) {
    throw new Error("No caption tracks found for this video.");
  }

  // Step 4: Find the target language track
  const track = findJapaneseTrack(tracks, language);
  if (!track) {
    const availableLanguages = tracks
      .map((t) => t.languageCode)
      .filter((v, i, a) => a.indexOf(v) === i)
      .join(", ");
    throw new Error(
      `No ${language} subtitles found. Available: ${availableLanguages}`
    );
  }

  // Step 5: Fetch the subtitle data in JSON3 format
  const urlObj = new URL(track.baseUrl);
  urlObj.searchParams.set("fmt", "json3");
  urlObj.searchParams.delete("callback");
  if (track.languageCode !== language) {
    urlObj.searchParams.set("tlang", language);
  }
  const subtitleUrl = urlObj.toString();
  
  const subtitleResponse = await fetch(subtitleUrl);

  if (!subtitleResponse.ok) {
    throw new Error(
      `Failed to fetch subtitle data: HTTP ${subtitleResponse.status}`
    );
  }

  const textData = await subtitleResponse.text();
  if (!textData || textData.trim() === "") {
    throw new Error(`Subtitle response was empty (URL: ${subtitleUrl})`);
  }

  let json3Data;
  try {
    json3Data = JSON.parse(textData);
  } catch (err) {
    throw new Error(`Failed to parse subtitle JSON (preview: ${textData.slice(0, 100)})`);
  }

  // Step 6: Parse into our format
  const segments = parseJson3Subtitles(json3Data as Record<string, unknown>);
  const fullText = segments.map((s) => s.text).join(" ");

  return {
    videoId,
    language,
    segments,
    fullText,
    trackName: track.languageCode !== language ? `${track.name} (Auto-translated)` : track.name,
    isAutoGenerated: track.isAutoGenerated,
  };
}

/**
 * Fetch subtitles for a YouTube video.
 *
 * Must run in the background service worker (not content scripts)
 * to avoid CORS restrictions.
 */
export async function fetchSubtitles(
  videoUrl: string,
  language: string = "ja"
): Promise<SubtitleFetchResult> {
  const videoId = extractVideoId(videoUrl);
  if (!videoId) {
    throw new Error(`Could not extract video ID from URL: ${videoUrl}`);
  }

  // Step 1: Fetch the YouTube watch page
  const pageUrl = `https://www.youtube.com/watch?v=${videoId}`;
  const pageResponse = await fetch(pageUrl, {
    headers: {
      // Pretend to be a normal browser to avoid bot detection
      "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      "Accept-Language": "ja,en-US;q=0.9,en;q=0.8",
    },
  });

  if (!pageResponse.ok) {
    throw new Error(
      `Failed to fetch YouTube page: HTTP ${pageResponse.status}`
    );
  }

  const html = await pageResponse.text();

  // Step 2: Extract the player response
  const playerResponse = parsePlayerResponse(html);
  if (!playerResponse) {
    throw new Error(
      "Could not find player response in YouTube page. The video may be unavailable."
    );
  }

  return fetchSubtitlesFromPlayerResponse(playerResponse, videoId, language);
}

/**
 * Get available caption tracks for a YouTube video.
 * Used for the track selector UI.
 */
export async function fetchCaptionTracks(
  videoUrl: string
): Promise<CaptionTrack[]> {
  const videoId = extractVideoId(videoUrl);
  if (!videoId) return [];

  const pageUrl = `https://www.youtube.com/watch?v=${videoId}`;
  const pageResponse = await fetch(pageUrl, {
    headers: {
      "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      "Accept-Language": "ja,en-US;q=0.9,en;q=0.8",
    },
  });

  if (!pageResponse.ok) return [];

  const html = await pageResponse.text();
  const playerResponse = parsePlayerResponse(html);
  if (!playerResponse) return [];

  return extractCaptionTracks(playerResponse);
}

export { extractVideoId };
