/**
 * YouTube subtitle extraction service.
 *
 * Extracts subtitle data from YouTube's internal player response.
 * Designed to run in the background service worker where CORS
 * restrictions don't apply due to host_permissions.
 *
 * Strategy:
 * 1. Fetch the YouTube watch page HTML
 * 2. Extract `ytInitialPlayerResponse` from the page source
 * 3. Parse caption tracks from the player response
 * 4. Fetch the selected track's subtitle data in JSON3 format
 * 5. Parse into our SubtitleSegment[] format
 */

import type {
  CaptionTrack,
  SubtitleSegment,
  SubtitleFetchResult,
} from "~types";

/** Extract video ID from various YouTube URL formats */
function extractVideoId(url: string): string | null {
  const patterns = [
    /[?&]v=([a-zA-Z0-9_-]{11})/,
    /youtu\.be\/([a-zA-Z0-9_-]{11})/,
    /youtube\.com\/embed\/([a-zA-Z0-9_-]{11})/,
  ];

  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) return match[1];
  }

  return null;
}

/** Parse ytInitialPlayerResponse from YouTube page HTML */
function parsePlayerResponse(html: string): Record<string, unknown> | null {
  // YouTube embeds player data in a script tag as:
  //   var ytInitialPlayerResponse = {...};
  // We use a regex that matches until the next variable declaration or end of script
  const patterns = [
    /ytInitialPlayerResponse\s*=\s*(\{.+?\})\s*;\s*(?:var\s|<\/script>)/s,
    /\["ytInitialPlayerResponse"\]\s*=\s*(\{.+?\})\s*;\s*(?:var\s|<\/script>)/s
  ];

  for (const pattern of patterns) {
    const match = html.match(pattern);
    if (match) {
      try {
        return JSON.parse(match[1]);
      } catch (e) {
        console.warn("Hakkutsu: Failed to parse ytInitialPlayerResponse regex match", e);
      }
    }
  }

  // Fallback: manual string extraction
  const marker = "ytInitialPlayerResponse = ";
  const startIdx = html.indexOf(marker);
  if (startIdx !== -1) {
    const jsonStart = startIdx + marker.length;
    const scriptEnd = html.indexOf("</script>", jsonStart);
    if (scriptEnd !== -1) {
      let candidate = html.substring(jsonStart, scriptEnd).trim();
      const lastBrace = candidate.lastIndexOf("};");
      if (lastBrace !== -1) {
        candidate = candidate.substring(0, lastBrace + 1);
        try {
          return JSON.parse(candidate);
        } catch (e) {
          console.warn("Hakkutsu: Failed to parse ytInitialPlayerResponse fallback match", e);
        }
      }
    }
  }

  return null;
}

/** Extract caption tracks from the player response */
function extractCaptionTracks(
  playerResponse: Record<string, unknown>
): CaptionTrack[] {
  const captions = (playerResponse as Record<string, Record<string, unknown>>)
    ?.captions;
  if (!captions) return [];

  const renderer = (
    captions as Record<string, Record<string, unknown>>
  )?.playerCaptionsTracklistRenderer;
  if (!renderer) return [];

  const captionTracks = (renderer as Record<string, unknown[]>)?.captionTracks;
  if (!Array.isArray(captionTracks)) return [];

  return captionTracks.map(
    (track: Record<string, unknown>): CaptionTrack => ({
      baseUrl: (track.baseUrl as string) || (track.url as string) || "",
      languageCode: (track.languageCode as string) || "",
      name: captionTrackName(track.name || track.displayName || track.languageName),
      kind: (track.kind as string) || "",
      isAutoGenerated: (track.kind as string) === "asr" || typeof track.vssId === "string" && track.vssId.startsWith("a."),
    })
  );
}

function captionTrackName(value: unknown): string {
  if (typeof value === "string") return value;
  if (!value || typeof value !== "object") return "";
  const text = value as {
    simpleText?: string;
    runs?: Array<{ text?: string }>;
  };
  return text.simpleText || text.runs?.map((run) => run.text || "").join("") || "";
}

/** Represents a single event in YouTube's JSON3 subtitle format */
interface Json3Event {
  tStartMs?: number;
  dDurationMs?: number;
  aAppend?: number | boolean;
  segs?: Array<{
    utf8?: string;
    tOffsetMs?: number;
    acAsrConf?: number;
  }>;
}

/** Parse YouTube JSON3 subtitle format into SubtitleSegment[] */
function parseJson3Subtitles(json3Data: Record<string, unknown>): SubtitleSegment[] {
  const events = (json3Data as { events?: Json3Event[] }).events;
  if (!Array.isArray(events)) return [];

  const segments: SubtitleSegment[] = [];

  for (const event of events) {
    // Skip events without segments (e.g. format/style events)
    if (!event.segs || event.tStartMs == null) continue;

    const text = event.segs
      .map((seg) => seg.utf8 || "")
      .join("")
      .replace(/\n/g, " ")
      .trim();

    if (!text) continue;

    const eventStart = event.tStartMs / 1000;
    const eventDuration = (event.dDurationMs || 0) / 1000;
    const words = event.segs
      .map((seg, index) => {
        const wordText = (seg.utf8 || "").replace(/\n/g, " ");
        if (!wordText.trim()) return null;
        const offsetMs = Math.max(0, Number(seg.tOffsetMs) || 0);
        const nextOffsetMs = Math.max(
          offsetMs,
          Number(event.segs?.[index + 1]?.tOffsetMs) || event.dDurationMs || 0
        );
        return {
          text: wordText.trim(),
          start: eventStart + offsetMs / 1000,
          duration: Math.max(0, nextOffsetMs - offsetMs) / 1000,
        };
      })
      .filter((word): word is NonNullable<typeof word> => word !== null);

    segments.push({
      text,
      start: eventStart,
      duration: eventDuration,
      words: words.length > 0 ? words : undefined,
      append: Boolean(event.aAppend),
    });
  }

  return segments;
}

/**
 * Find the best caption track from available tracks.
 * `auto` keeps subtitle interception language-agnostic; an explicit language
 * still prefers a manually-created track over an auto-generated one.
 */
function findCaptionTrack(
  tracks: CaptionTrack[],
  language: string = "auto"
): CaptionTrack | null {
  const normalizedLanguage = language.trim().toLowerCase();
  if (!normalizedLanguage || normalizedLanguage === "auto" || normalizedLanguage === "*") {
    return tracks.find((track) => !track.isAutoGenerated) ?? tracks[0] ?? null;
  }

  const matchesLanguage = (track: CaptionTrack) =>
    track.languageCode.toLowerCase() === normalizedLanguage ||
    track.languageCode.toLowerCase().startsWith(`${normalizedLanguage}-`);

  // Prefer manual subtitles
  const manual = tracks.find(
    (t) => matchesLanguage(t) && !t.isAutoGenerated
  );
  if (manual) return manual;

  // Fall back to auto-generated
  const auto = tracks.find(
    (t) => matchesLanguage(t) && t.isAutoGenerated
  );
  if (auto) return auto;

  return null;
}

function playerResponseVideoId(
  playerResponse: Record<string, unknown>
): string | null {
  const videoDetails = playerResponse.videoDetails as
    | { videoId?: unknown }
    | undefined;
  return typeof videoDetails?.videoId === "string"
    ? videoDetails.videoId
    : null;
}

function decodeCaptionText(value: string): string {
  const entities: Record<string, string> = {
    amp: "&",
    apos: "'",
    gt: ">",
    lt: "<",
    quot: "\"",
  };
  return value
    .replace(/<[^>]+>/g, "")
    .replace(/&#(\d+);/g, (_match, code) => String.fromCodePoint(Number(code)))
    .replace(/&#x([0-9a-f]+);/gi, (_match, code) =>
      String.fromCodePoint(Number.parseInt(code, 16))
    )
    .replace(/&([a-z]+);/gi, (match, name) => entities[name] ?? match)
    .replace(/\s+/g, " ")
    .trim();
}

function parseXmlSubtitles(text: string): SubtitleSegment[] {
  const segments: SubtitleSegment[] = [];
  const cuePattern = /<text\b([^>]*)>([\s\S]*?)<\/text>/gi;
  let match: RegExpExecArray | null;
  while ((match = cuePattern.exec(text))) {
    const attributes = match[1];
    const startMatch = attributes.match(/\bstart="([^"]+)"/i);
    const durationMatch = attributes.match(/\bdur="([^"]+)"/i);
    if (!startMatch) continue;
    const cueText = decodeCaptionText(match[2]);
    if (!cueText) continue;
    segments.push({
      text: cueText,
      start: Number(startMatch[1]) || 0,
      duration: Number(durationMatch?.[1]) || 0,
    });
  }
  return segments;
}

function parseVttTimestamp(value: string): number | null {
  const parts = value.trim().split(":").map(Number);
  if (parts.some(Number.isNaN) || (parts.length !== 2 && parts.length !== 3)) {
    return null;
  }
  const seconds = parts.pop()!;
  const minutes = parts.pop()!;
  const hours = parts.pop() || 0;
  return hours * 3600 + minutes * 60 + seconds;
}

function parseVttSubtitles(text: string): SubtitleSegment[] {
  const normalized = text.replace(/\r\n?/g, "\n");
  const blocks = normalized.split(/\n\s*\n/);
  const segments: SubtitleSegment[] = [];
  for (const block of blocks) {
    const lines = block.split("\n").map((line) => line.trim()).filter(Boolean);
    const timingIndex = lines.findIndex((line) => line.includes("-->"));
    if (timingIndex < 0) continue;
    const [rawStart, rawEnd] = lines[timingIndex].split("-->", 2);
    const start = parseVttTimestamp(rawStart);
    const end = parseVttTimestamp(rawEnd.split(/\s+/, 1)[0]);
    const cueText = decodeCaptionText(lines.slice(timingIndex + 1).join(" "));
    if (start == null || end == null || !cueText) continue;
    segments.push({ text: cueText, start, duration: Math.max(0, end - start) });
  }
  return segments;
}

async function fetchTrackSegments(
  track: CaptionTrack,
  videoId: string
): Promise<SubtitleSegment[]> {
  if (!track.baseUrl) {
    throw new Error("The selected YouTube caption track has no URL.");
  }

  const baseUrl = new URL(track.baseUrl);
  const trackVideoId = baseUrl.searchParams.get("v");
  if (trackVideoId && trackVideoId !== videoId) {
    throw new Error(
      `YouTube player response is stale (track ${trackVideoId}, current video ${videoId}).`
    );
  }

  const attempts: Array<{
    format: "json3" | "xml" | "vtt";
    url: URL;
  }> = [];
  const json3Url = new URL(baseUrl);
  json3Url.searchParams.set("fmt", "json3");
  json3Url.searchParams.delete("callback");
  attempts.push({ format: "json3", url: json3Url });

  const xmlUrl = new URL(baseUrl);
  xmlUrl.searchParams.delete("fmt");
  xmlUrl.searchParams.delete("callback");
  attempts.push({ format: "xml", url: xmlUrl });

  const vttUrl = new URL(baseUrl);
  vttUrl.searchParams.set("fmt", "vtt");
  vttUrl.searchParams.delete("callback");
  attempts.push({ format: "vtt", url: vttUrl });

  const failures: string[] = [];
  for (const attempt of attempts) {
    try {
      const response = await fetch(attempt.url.toString(), {
        credentials: "include",
        cache: "no-store",
      });
      if (!response.ok) {
        failures.push(`${attempt.format}: HTTP ${response.status}`);
        continue;
      }
      const text = await response.text();
      if (!text.trim()) {
        failures.push(`${attempt.format}: empty`);
        continue;
      }
      const segments =
        attempt.format === "json3"
          ? parseJson3Subtitles(JSON.parse(text) as Record<string, unknown>)
          : attempt.format === "xml"
            ? parseXmlSubtitles(text)
            : parseVttSubtitles(text);
      if (segments.length > 0) return segments;
      failures.push(`${attempt.format}: no cues`);
    } catch (error) {
      failures.push(
        `${attempt.format}: ${error instanceof Error ? error.message : String(error)}`
      );
    }
  }

  const poTokenHint = baseUrl.searchParams.get("exp") === "xpe"
    ? " This track requires a YouTube PO token."
    : "";
  throw new Error(
    `YouTube returned no usable data for caption track "${track.languageCode}" (${failures.join("; ")}).${poTokenHint}`
  );
}

export async function fetchSubtitlesFromPlayerResponse(
  playerResponse: Record<string, unknown>,
  videoId: string,
  language: string = "ja"
): Promise<SubtitleFetchResult> {
  const responseVideoId = playerResponseVideoId(playerResponse);
  if (responseVideoId && responseVideoId !== videoId) {
    throw new Error(
      `YouTube player response belongs to ${responseVideoId}, not the current video ${videoId}.`
    );
  }

  // Step 3: Get caption tracks
  const tracks = extractCaptionTracks(playerResponse);
  if (tracks.length === 0) {
    throw new Error("No caption tracks found for this video.");
  }

  // Step 4: Find the target language track
  const track = findCaptionTrack(tracks, language);
  if (!track) {
    const availableLanguages = tracks
      .map((t) => t.languageCode)
      .filter((v, i, a) => a.indexOf(v) === i)
      .join(", ");
    throw new Error(
      `No ${language} subtitles found. Available: ${availableLanguages}`
    );
  }

  // Fetching happens in the extension background worker. This preserves the
  // exact signed URL from the current player while avoiding content-script
  // CORS restrictions.
  const segments = await fetchTrackSegments(track, videoId);
  const fullText = segments.map((s) => s.text).join(" ");

  return {
    videoId,
    language: track.languageCode,
    segments,
    fullText,
    trackName: track.name || track.languageCode,
    isAutoGenerated: track.isAutoGenerated,
    source: "player",
  };
}

/**
 * Fetch subtitles for a YouTube video.
 *
 * Must run in the background service worker (not content scripts)
 * to avoid CORS restrictions.
 */
export async function fetchSubtitles(
  videoUrl: string,
  language: string = "ja"
): Promise<SubtitleFetchResult> {
  const videoId = extractVideoId(videoUrl);
  if (!videoId) {
    throw new Error(`Could not extract video ID from URL: ${videoUrl}`);
  }

  // Step 1: Fetch the YouTube watch page
  const pageUrl = `https://www.youtube.com/watch?v=${videoId}`;
  const pageResponse = await fetch(pageUrl, {
    headers: {
      // Pretend to be a normal browser to avoid bot detection
      "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      "Accept-Language": "ja,en-US;q=0.9,en;q=0.8",
    },
  });

  if (!pageResponse.ok) {
    throw new Error(
      `Failed to fetch YouTube page: HTTP ${pageResponse.status}`
    );
  }

  const html = await pageResponse.text();

  // Step 2: Extract the player response
  const playerResponse = parsePlayerResponse(html);
  if (!playerResponse) {
    throw new Error(
      "Could not find player response in YouTube page. The video may be unavailable."
    );
  }

  return fetchSubtitlesFromPlayerResponse(playerResponse, videoId, language);
}

/**
 * Get available caption tracks for a YouTube video.
 * Used for the track selector UI.
 */
export async function fetchCaptionTracks(
  videoUrl: string
): Promise<CaptionTrack[]> {
  const videoId = extractVideoId(videoUrl);
  if (!videoId) return [];

  const pageUrl = `https://www.youtube.com/watch?v=${videoId}`;
  const pageResponse = await fetch(pageUrl, {
    headers: {
      "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      "Accept-Language": "ja,en-US;q=0.9,en;q=0.8",
    },
  });

  if (!pageResponse.ok) return [];

  const html = await pageResponse.text();
  const playerResponse = parsePlayerResponse(html);
  if (!playerResponse) return [];

  return extractCaptionTracks(playerResponse);
}

export {
  extractCaptionTracks,
  extractVideoId,
  findCaptionTrack,
  parseJson3Subtitles,
  parseVttSubtitles,
  parseXmlSubtitles,
  playerResponseVideoId,
};
