import { useState, useEffect, useRef } from "react";
import { X, Settings, Info, FolderOpen, Globe, Check, ChevronDown, Search, ArrowLeft, Loader2, Download } from "lucide-react";
import { useTranslation } from "~lib/languages/locales";
import { useSettingsStore } from "~lib/utils/settings";
import { readSubtitleFile, parsedToSubtitleFetchResult } from "~lib/services/subtitle-parsers";
import { jimakuService, type JimakuEntry, type JimakuFile } from "~lib/services/jimaku-service";
import type { SubtitleFetchResult } from "~lib/types";
import type { YouTubePlayerTrack } from "~lib/services/youtube-tab-extractor";

export interface SubtitleTrackOption {
  id: string;
  name: string;
  languageCode: string;
  isAutoGenerated?: boolean;
  rawTrack?: YouTubePlayerTrack | TextTrack;
  fetchResult?: SubtitleFetchResult;
}

export interface SelectSubtitlesModalProps {
  isOpen: boolean;
  onClose: () => void;
  videoTitle: string;
  availableTracks: SubtitleTrackOption[];
  currentTrackId?: string;
  secondaryTrackId?: string;
  onSelectTrack: (track: SubtitleTrackOption) => Promise<void> | void;
  onSelectSecondaryTrack?: (track: SubtitleTrackOption | null) => Promise<void> | void;
  onCustomSubtitleLoaded: (result: SubtitleFetchResult) => void;
  onOpenSettings?: () => void;
}

export function SelectSubtitlesModal({
  isOpen,
  onClose,
  videoTitle,
  availableTracks,
  currentTrackId,
  secondaryTrackId,
  onSelectTrack,
  onSelectSecondaryTrack,
  onCustomSubtitleLoaded,
  onOpenSettings,
}: SelectSubtitlesModalProps) {
  const { t } = useTranslation();
  const { settings, updateSettings } = useSettingsStore();

  const [mode, setMode] = useState<"select" | "jimaku">("select");
  const [showInfo, setShowInfo] = useState(true);
  const [rememberChoices, setRememberChoices] = useState(true);
  const [editableTitle, setEditableTitle] = useState(videoTitle);
  const [selectedTrack1, setSelectedTrack1] = useState<string>(currentTrackId || "");
  const [selectedTrack2, setSelectedTrack2] = useState<string>(secondaryTrackId || "");

  // Jimaku search state
  const [searchQuery, setSearchQuery] = useState(videoTitle);
  const [apiKeyInput, setApiKeyInput] = useState(settings.jimakuApiKey || "");
  const [showApiKeyInput, setShowApiKeyInput] = useState(!settings.jimakuApiKey);
  const [searching, setSearching] = useState(false);
  const [entries, setEntries] = useState<JimakuEntry[]>([]);
  const [selectedEntry, setSelectedEntry] = useState<JimakuEntry | null>(null);
  const [entryFiles, setEntryFiles] = useState<JimakuFile[]>([]);
  const [loadingFiles, setLoadingFiles] = useState(false);
  const [downloadingFileId, setDownloadingFileId] = useState<number | null>(null);
  const [jimakuError, setJimakuError] = useState<string | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (videoTitle) {
      setEditableTitle(videoTitle);
      setSearchQuery(videoTitle);
    }
  }, [videoTitle]);

  useEffect(() => {
    if (currentTrackId) {
      setSelectedTrack1(currentTrackId);
    }
  }, [currentTrackId]);

  if (!isOpen) return null;

  const handleOpenFilePicker = () => {
    fileInputRef.current?.click();
  };

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    try {
      const parsed = await readSubtitleFile(file);
      const result = parsedToSubtitleFetchResult(parsed, file.name);
      onCustomSubtitleLoaded(result);
      onClose();
    } catch (err) {
      alert(err instanceof Error ? err.message : "Error reading subtitle file");
    } finally {
      if (fileInputRef.current) fileInputRef.current.value = "";
    }
  };

  const handleTrack1Change = async (val: string) => {
    if (val === "__open_files__") {
      handleOpenFilePicker();
      return;
    }
    if (val === "__search_online__") {
      setMode("jimaku");
      return;
    }
    setSelectedTrack1(val);
    const track = availableTracks.find((t) => t.id === val);
    if (track) {
      await onSelectTrack(track);
    }
  };

  const handleTrack2Change = (val: string) => {
    setSelectedTrack2(val);
    if (val === "" || val === "__empty__") {
      onSelectSecondaryTrack?.(null);
      return;
    }
    const track = availableTracks.find((t) => t.id === val);
    if (track) {
      onSelectSecondaryTrack?.(track);
    }
  };

  const handleSearchJimaku = async () => {
    if (!searchQuery.trim()) return;
    setSearching(true);
    setJimakuError(null);
    setSelectedEntry(null);
    setEntryFiles([]);

    try {
      const results = await jimakuService.searchEntries(searchQuery, apiKeyInput || settings.jimakuApiKey || "");
      setEntries(results);
      if (results.length === 0) {
        setJimakuError("Không tìm thấy phim/anime phù hợp trên Jimaku.cc.");
      }
    } catch (err) {
      setJimakuError(err instanceof Error ? err.message : "Jimaku search failed");
    } finally {
      setSearching(false);
    }
  };

  const handleSelectEntry = async (entry: JimakuEntry) => {
    setSelectedEntry(entry);
    setLoadingFiles(true);
    setJimakuError(null);

    try {
      const files = await jimakuService.getEntryFiles(entry.id, apiKeyInput || settings.jimakuApiKey || "");
      setEntryFiles(files);
      if (files.length === 0) {
        setJimakuError("Chưa có file phụ đề cho mục này trên Jimaku.cc.");
      }
    } catch (err) {
      setJimakuError(err instanceof Error ? err.message : "Failed to load files");
    } finally {
      setLoadingFiles(false);
    }
  };

  const handleDownloadFile = async (file: JimakuFile) => {
    setDownloadingFileId(file.id);
    setJimakuError(null);

    try {
      const result = await jimakuService.downloadSubtitle(file, apiKeyInput || settings.jimakuApiKey || "");
      onCustomSubtitleLoaded(result);
      onClose();
    } catch (err) {
      setJimakuError(err instanceof Error ? err.message : "Failed to download subtitle");
    } finally {
      setDownloadingFileId(null);
    }
  };

  const handleSaveApiKey = () => {
    updateSettings({ jimakuApiKey: apiKeyInput });
    setShowApiKeyInput(false);
  };

  return (
    <div
      className="hk-modal-backdrop"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
      style={{
        position: "fixed",
        inset: 0,
        backgroundColor: "rgba(0, 0, 0, 0.75)",
        backdropFilter: "blur(6px)",
        zIndex: 2147483647,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "16px",
        fontFamily: "system-ui, -apple-system, sans-serif",
      }}
    >
      <input
        type="file"
        ref={fileInputRef}
        onChange={handleFileChange}
        accept=".srt,.vtt,.ass,.ssa"
        style={{ display: "none" }}
      />

      <div
        className="hk-select-sub-modal"
        style={{
          width: "100%",
          maxWidth: "480px",
          backgroundColor: "#18181b",
          border: "1px solid rgba(255, 255, 255, 0.12)",
          borderRadius: "14px",
          boxShadow: "0 20px 40px rgba(0, 0, 0, 0.6), 0 0 0 1px rgba(168, 85, 247, 0.2)",
          color: "#f4f4f5",
          overflow: "hidden",
          display: "flex",
          flexDirection: "column",
          maxHeight: "90vh",
          animation: "hk-fade-in 0.2s ease-out",
        }}
      >
        {/* Header */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            padding: "16px 20px",
            borderBottom: "1px solid rgba(255, 255, 255, 0.08)",
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
            {mode === "jimaku" && (
              <button
                onClick={() => setMode("select")}
                style={{
                  background: "transparent",
                  border: "none",
                  color: "#a1a1aa",
                  cursor: "pointer",
                  padding: "4px",
                  display: "flex",
                  alignItems: "center",
                }}
              >
                <ArrowLeft size={18} />
              </button>
            )}
            <h2 style={{ fontSize: "17px", fontWeight: 700, margin: 0, color: "#fff" }}>
              {mode === "select" ? t("sub_modal_title") : "Jimaku.cc Subtitle Search"}
            </h2>
          </div>

          <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
            {onOpenSettings && (
              <button
                onClick={onOpenSettings}
                title="Settings"
                style={{
                  background: "transparent",
                  border: "none",
                  color: "#a1a1aa",
                  cursor: "pointer",
                  padding: "6px",
                  borderRadius: "6px",
                  display: "flex",
                  alignItems: "center",
                }}
              >
                <Settings size={17} />
              </button>
            )}
            <button
              onClick={onClose}
              title="Close"
              style={{
                background: "transparent",
                border: "none",
                color: "#a1a1aa",
                cursor: "pointer",
                padding: "6px",
                borderRadius: "6px",
                display: "flex",
                alignItems: "center",
              }}
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Modal Body */}
        <div style={{ padding: "20px", overflowY: "auto", display: "flex", flexDirection: "column", gap: "18px" }}>
          {mode === "select" ? (
            <>
              {/* Info banner */}
              {showInfo && (
                <div
                  style={{
                    backgroundColor: "rgba(30, 41, 59, 0.7)",
                    border: "1px solid rgba(56, 189, 248, 0.25)",
                    borderRadius: "10px",
                    padding: "12px 14px",
                    display: "flex",
                    alignItems: "flex-start",
                    gap: "12px",
                    fontSize: "12px",
                    lineHeight: "1.4",
                    color: "#94a3b8",
                  }}
                >
                  <Info size={18} style={{ color: "#38bdf8", flexShrink: 0, marginTop: "1px" }} />
                  <div style={{ flex: 1 }}>{t("sub_modal_info")}</div>
                  <button
                    onClick={() => setShowInfo(false)}
                    style={{
                      background: "transparent",
                      border: "none",
                      color: "#e2e8f0",
                      fontWeight: 700,
                      cursor: "pointer",
                      fontSize: "11px",
                      padding: "2px 6px",
                    }}
                  >
                    OK
                  </button>
                </div>
              )}

              {/* Video Name */}
              <div>
                <label style={{ display: "block", fontSize: "11px", color: "#a1a1aa", marginBottom: "6px", fontWeight: 600 }}>
                  {t("sub_modal_video_name")}
                </label>
                <input
                  type="text"
                  value={editableTitle}
                  onChange={(e) => setEditableTitle(e.target.value)}
                  style={{
                    width: "100%",
                    padding: "10px 12px",
                    borderRadius: "8px",
                    backgroundColor: "#27272a",
                    border: "1px solid rgba(255, 255, 255, 0.1)",
                    color: "#f4f4f5",
                    fontSize: "13px",
                    boxSizing: "border-box",
                  }}
                />
              </div>

              {/* Subtitle Track 1 */}
              <div>
                <label style={{ display: "block", fontSize: "11px", color: "#e879f9", marginBottom: "6px", fontWeight: 600 }}>
                  {t("sub_modal_track_primary")}
                </label>
                <div style={{ position: "relative" }}>
                  <select
                    value={selectedTrack1}
                    onChange={(e) => handleTrack1Change(e.target.value)}
                    style={{
                      width: "100%",
                      padding: "11px 14px",
                      borderRadius: "8px",
                      backgroundColor: "#27272a",
                      border: "1.5px solid rgba(168, 85, 247, 0.5)",
                      color: "#fff",
                      fontSize: "13.5px",
                      cursor: "pointer",
                      appearance: "none",
                      boxSizing: "border-box",
                    }}
                  >
                    {availableTracks.length === 0 ? (
                      <option value="">{t("sub_modal_empty")}</option>
                    ) : (
                      availableTracks.map((track) => (
                        <option key={track.id} value={track.id}>
                          {track.name} {track.isAutoGenerated ? "(Auto-generated)" : ""}
                        </option>
                      ))
                    )}
                    <option disabled style={{ borderTop: "1px solid #444" }}>──────────</option>
                    <option value="__open_files__">{t("sub_modal_open_files")}</option>
                    <option value="__search_online__">{t("sub_modal_search_online")}</option>
                  </select>
                  <ChevronDown
                    size={16}
                    style={{
                      position: "absolute",
                      right: "12px",
                      top: "50%",
                      transform: "translateY(-50%)",
                      pointerEvents: "none",
                      color: "#a1a1aa",
                    }}
                  />
                </div>
              </div>

              {/* Subtitle Track 2 (Optional) */}
              <div>
                <label style={{ display: "block", fontSize: "11px", color: "#a1a1aa", marginBottom: "6px", fontWeight: 600 }}>
                  {t("sub_modal_track_secondary")}
                </label>
                <div style={{ position: "relative" }}>
                  <select
                    value={selectedTrack2}
                    onChange={(e) => handleTrack2Change(e.target.value)}
                    style={{
                      width: "100%",
                      padding: "11px 14px",
                      borderRadius: "8px",
                      backgroundColor: "#27272a",
                      border: "1px solid rgba(255, 255, 255, 0.1)",
                      color: selectedTrack2 ? "#fff" : "#71717a",
                      fontSize: "13px",
                      cursor: "pointer",
                      appearance: "none",
                      boxSizing: "border-box",
                    }}
                  >
                    <option value="__empty__">{t("sub_modal_empty")}</option>
                    {availableTracks.map((track) => (
                      <option key={`sec_${track.id}`} value={track.id}>
                        {track.name}
                      </option>
                    ))}
                  </select>
                  <ChevronDown
                    size={16}
                    style={{
                      position: "absolute",
                      right: "12px",
                      top: "50%",
                      transform: "translateY(-50%)",
                      pointerEvents: "none",
                      color: "#a1a1aa",
                    }}
                  />
                </div>
              </div>

              {/* Remember choice switch */}
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", paddingTop: "4px" }}>
                <span style={{ fontSize: "12.5px", color: "#d4d4d8" }}>{t("sub_modal_remember")}</span>
                <label
                  style={{
                    position: "relative",
                    display: "inline-block",
                    width: "36px",
                    height: "20px",
                    cursor: "pointer",
                  }}
                >
                  <input
                    type="checkbox"
                    checked={rememberChoices}
                    onChange={(e) => setRememberChoices(e.target.checked)}
                    style={{ opacity: 0, width: 0, height: 0 }}
                  />
                  <span
                    style={{
                      position: "absolute",
                      inset: 0,
                      backgroundColor: rememberChoices ? "#a855f7" : "#3f3f46",
                      borderRadius: "20px",
                      transition: "0.2s",
                    }}
                  />
                  <span
                    style={{
                      position: "absolute",
                      top: "2px",
                      left: rememberChoices ? "18px" : "2px",
                      width: "16px",
                      height: "16px",
                      borderRadius: "50%",
                      backgroundColor: "#fff",
                      transition: "0.2s",
                    }}
                  />
                </label>
              </div>
            </>
          ) : (
            /* Jimaku Search Mode */
            <div style={{ display: "flex", flexDirection: "column", gap: "14px" }}>
              {/* API Key Toggle/Prompt */}
              {showApiKeyInput ? (
                <div
                  style={{
                    backgroundColor: "rgba(39, 39, 42, 0.8)",
                    border: "1px solid rgba(255, 255, 255, 0.1)",
                    borderRadius: "8px",
                    padding: "10px 12px",
                  }}
                >
                  <div style={{ fontSize: "11px", color: "#a1a1aa", marginBottom: "4px" }}>
                    Jimaku.cc API Key (Optional):
                  </div>
                  <div style={{ display: "flex", gap: "8px" }}>
                    <input
                      type="password"
                      placeholder="Paste API Key..."
                      value={apiKeyInput}
                      onChange={(e) => setApiKeyInput(e.target.value)}
                      style={{
                        flex: 1,
                        padding: "6px 8px",
                        backgroundColor: "#18181b",
                        border: "1px solid #3f3f46",
                        borderRadius: "6px",
                        color: "#fff",
                        fontSize: "12px",
                      }}
                    />
                    <button
                      onClick={handleSaveApiKey}
                      style={{
                        padding: "6px 12px",
                        backgroundColor: "#a855f7",
                        color: "#fff",
                        border: "none",
                        borderRadius: "6px",
                        fontWeight: 600,
                        fontSize: "12px",
                        cursor: "pointer",
                      }}
                    >
                      Save
                    </button>
                  </div>
                </div>
              ) : null}

              {/* Search bar */}
              <div style={{ display: "flex", gap: "8px" }}>
                <input
                  type="text"
                  placeholder="Anime / Drama title..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && handleSearchJimaku()}
                  style={{
                    flex: 1,
                    padding: "10px 12px",
                    borderRadius: "8px",
                    backgroundColor: "#27272a",
                    border: "1px solid rgba(255, 255, 255, 0.1)",
                    color: "#fff",
                    fontSize: "13px",
                  }}
                />
                <button
                  onClick={handleSearchJimaku}
                  disabled={searching}
                  style={{
                    padding: "0 16px",
                    borderRadius: "8px",
                    backgroundColor: "#a855f7",
                    color: "#fff",
                    border: "none",
                    fontWeight: 600,
                    fontSize: "13px",
                    cursor: "pointer",
                    display: "flex",
                    alignItems: "center",
                    gap: "6px",
                  }}
                >
                  {searching ? <Loader2 size={16} className="hk-spin" /> : <Search size={16} />}
                  Search
                </button>
              </div>

              {jimakuError && (
                <div style={{ fontSize: "12px", color: "#f87171", padding: "4px 2px" }}>
                  {jimakuError}
                </div>
              )}

              {/* Results List */}
              {!selectedEntry ? (
                <div style={{ maxHeight: "240px", overflowY: "auto", display: "flex", flexDirection: "column", gap: "6px" }}>
                  {entries.map((entry) => (
                    <div
                      key={entry.id}
                      onClick={() => handleSelectEntry(entry)}
                      style={{
                        padding: "10px 12px",
                        backgroundColor: "#27272a",
                        borderRadius: "8px",
                        cursor: "pointer",
                        border: "1px solid transparent",
                        transition: "all 0.15s ease",
                      }}
                      onMouseEnter={(e) => (e.currentTarget.style.borderColor = "#a855f7")}
                      onMouseLeave={(e) => (e.currentTarget.style.borderColor = "transparent")}
                    >
                      <div style={{ fontSize: "13px", fontWeight: 600, color: "#fff" }}>
                        {entry.japanese_name || entry.name}
                      </div>
                      {entry.english_name && entry.english_name !== entry.name && (
                        <div style={{ fontSize: "11px", color: "#a1a1aa" }}>{entry.english_name}</div>
                      )}
                    </div>
                  ))}
                </div>
              ) : (
                /* Files under selected entry */
                <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                  <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                    <span style={{ fontSize: "12px", fontWeight: 600, color: "#c084fc" }}>
                      {selectedEntry.japanese_name || selectedEntry.name}
                    </span>
                    <button
                      onClick={() => setSelectedEntry(null)}
                      style={{ background: "transparent", border: "none", color: "#a1a1aa", fontSize: "11px", cursor: "pointer" }}
                    >
                      Change title
                    </button>
                  </div>

                  {loadingFiles ? (
                    <div style={{ display: "flex", alignItems: "center", gap: "8px", color: "#a1a1aa", fontSize: "12px", padding: "16px 0" }}>
                      <Loader2 size={16} className="hk-spin" /> Loading subtitle files...
                    </div>
                  ) : (
                    <div style={{ maxHeight: "200px", overflowY: "auto", display: "flex", flexDirection: "column", gap: "6px" }}>
                      {entryFiles.map((file) => (
                        <div
                          key={file.id}
                          style={{
                            display: "flex",
                            alignItems: "center",
                            justifyContent: "space-between",
                            padding: "8px 10px",
                            backgroundColor: "#27272a",
                            borderRadius: "6px",
                          }}
                        >
                          <span style={{ fontSize: "12px", color: "#f4f4f5", wordBreak: "break-all" }}>
                            {file.name}
                          </span>
                          <button
                            onClick={() => handleDownloadFile(file)}
                            disabled={downloadingFileId === file.id}
                            style={{
                              padding: "4px 10px",
                              backgroundColor: "#a855f7",
                              color: "#fff",
                              border: "none",
                              borderRadius: "4px",
                              fontSize: "11px",
                              fontWeight: 600,
                              cursor: "pointer",
                              display: "flex",
                              alignItems: "center",
                              gap: "4px",
                              flexShrink: 0,
                            }}
                          >
                            {downloadingFileId === file.id ? (
                              <Loader2 size={12} className="hk-spin" />
                            ) : (
                              <Download size={12} />
                            )}
                            Load
                          </button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>
          )}
        </div>

        {/* Modal Footer Actions */}
        <div
          style={{
            padding: "16px 20px",
            borderTop: "1px solid rgba(255, 255, 255, 0.08)",
            display: "flex",
            alignItems: "center",
            justifyContent: "flex-end",
            gap: "10px",
            backgroundColor: "rgba(24, 24, 27, 0.95)",
          }}
        >
          {mode === "select" ? (
            <>
              <button
                onClick={handleOpenFilePicker}
                style={{
                  padding: "8px 14px",
                  background: "rgba(255, 255, 255, 0.06)",
                  border: "1px solid rgba(255, 255, 255, 0.15)",
                  color: "#f4f4f5",
                  borderRadius: "8px",
                  fontSize: "12px",
                  fontWeight: 600,
                  cursor: "pointer",
                  display: "flex",
                  alignItems: "center",
                  gap: "6px",
                }}
              >
                <FolderOpen size={14} />
                {t("sub_modal_btn_open_files")}
              </button>

              <button
                onClick={() => setMode("jimaku")}
                style={{
                  padding: "8px 14px",
                  background: "rgba(168, 85, 247, 0.15)",
                  border: "1px solid rgba(168, 85, 247, 0.4)",
                  color: "#d8b4fe",
                  borderRadius: "8px",
                  fontSize: "12px",
                  fontWeight: 600,
                  cursor: "pointer",
                  display: "flex",
                  alignItems: "center",
                  gap: "6px",
                }}
              >
                <Globe size={14} />
                {t("sub_modal_btn_search_online")}
              </button>

              <button
                onClick={onClose}
                style={{
                  padding: "8px 18px",
                  background: "#a855f7",
                  border: "none",
                  color: "#fff",
                  borderRadius: "8px",
                  fontSize: "12.5px",
                  fontWeight: 700,
                  cursor: "pointer",
                }}
              >
                OK
              </button>
            </>
          ) : (
            <button
              onClick={() => setMode("select")}
              style={{
                padding: "8px 16px",
                background: "#a855f7",
                border: "none",
                color: "#fff",
                borderRadius: "8px",
                fontSize: "12.5px",
                fontWeight: 600,
                cursor: "pointer",
              }}
            >
              Back to Track List
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
