import React, { useState, useEffect, useRef } from "react";
import { X, Settings, FolderOpen, Check, ChevronDown, Clock, Sliders, Volume2, Type, Subtitles } from "lucide-react";
import { useTranslation } from "~lib/locales";
import { readSubtitleFile, parsedToSubtitleFetchResult } from "~lib/services/subtitle-parsers";
import type { SubtitleFetchResult } from "~lib/utils/types";

export interface SubtitleTrackOption {
  id: string;
  name: string;
  languageCode: string;
  isAutoGenerated?: boolean;
  url?: string;
  fetchResult?: SubtitleFetchResult;
}

export interface SelectSubtitlesModalProps {
  isOpen: boolean;
  onClose: () => void;
  videoTitle: string;
  availableTracks: SubtitleTrackOption[];
  currentTrackId?: string;
  secondaryTrackId?: string;
  offset: number;
  onOffsetChange: (newOffset: number) => void;
  autoPause: boolean;
  onAutoPauseChange: (autoPause: boolean) => void;
  fontSize: number;
  onFontSizeChange: (size: number) => void;
  showFurigana?: boolean;
  onFuriganaChange?: (show: boolean) => void;
  onSelectTrack: (track: SubtitleTrackOption) => Promise<void> | void;
  onSelectSecondaryTrack: (track: SubtitleTrackOption | null) => Promise<void> | void;
  onCustomSubtitleLoaded: (result: SubtitleFetchResult) => void;
}

interface TrackSelectProps {
  label: string;
  labelColor?: string;
  value: string;
  onChange: (val: string) => void;
  tracks: SubtitleTrackOption[];
  allowEmpty?: boolean;
  emptyLabel?: string;
  allowAutoTranslate?: boolean;
  autoTranslateLabel?: string;
}

function CustomTrackDropdown({
  label,
  labelColor = "#a1a1aa",
  value,
  onChange,
  tracks,
  allowEmpty = false,
  emptyLabel = "None",
  allowAutoTranslate = false,
  autoTranslateLabel = "Auto-translate on demand",
}: TrackSelectProps) {
  const [open, setOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      const path = (e.composedPath && e.composedPath()) || [];
      if (
        dropdownRef.current &&
        !path.includes(dropdownRef.current) &&
        !dropdownRef.current.contains(e.target as Node)
      ) {
        setOpen(false);
      }
    };
    if (open) {
      document.addEventListener("mousedown", handleClickOutside);
    }
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [open]);

  const selectedTrack = tracks.find((t) => t.id === value);

  let displayLabel = emptyLabel;
  if (value === "__auto_translate__") {
    displayLabel = autoTranslateLabel;
  } else if (selectedTrack) {
    displayLabel = `${selectedTrack.name}${selectedTrack.isAutoGenerated ? " (Auto)" : ""}`;
  }

  return (
    <div style={{ position: "relative", marginBottom: "14px" }} ref={dropdownRef}>
      <label style={{ display: "block", fontSize: "11px", color: labelColor, marginBottom: "6px", fontWeight: 600 }}>
        {label}
      </label>
      <button
        type="button"
        onClick={(e) => {
          e.stopPropagation();
          setOpen((prev) => !prev);
        }}
        style={{
          width: "100%",
          padding: "10px 14px",
          borderRadius: "8px",
          backgroundColor: "#18181b",
          border: open ? "1.5px solid #a855f7" : "1px solid rgba(255, 255, 255, 0.12)",
          color: selectedTrack || value === "__auto_translate__" ? "#fff" : "#a1a1aa",
          fontSize: "13px",
          cursor: "pointer",
          boxSizing: "border-box",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          textAlign: "left",
          transition: "all 0.15s ease",
        }}
      >
        <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", marginRight: "8px" }}>
          {displayLabel}
        </span>
        <ChevronDown size={16} style={{ transform: open ? "rotate(180deg)" : "none", transition: "transform 0.2s" }} />
      </button>

      {open && (
        <div
          style={{
            position: "absolute",
            top: "calc(100% + 4px)",
            left: 0,
            right: 0,
            backgroundColor: "#18181b",
            border: "1px solid rgba(255, 255, 255, 0.15)",
            borderRadius: "8px",
            boxShadow: "0 12px 30px rgba(0,0,0,0.8)",
            zIndex: 10000,
            maxHeight: "220px",
            overflowY: "auto",
          }}
        >
          {allowEmpty && (
            <div
              onClick={() => {
                onChange("");
                setOpen(false);
              }}
              style={{
                padding: "9px 14px",
                fontSize: "13px",
                color: !value ? "#a855f7" : "#a1a1aa",
                cursor: "pointer",
                backgroundColor: !value ? "rgba(168, 85, 247, 0.1)" : "transparent",
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
              }}
            >
              <span>{emptyLabel}</span>
              {!value && <Check size={14} color="#a855f7" />}
            </div>
          )}

          {allowAutoTranslate && (
            <div
              onClick={() => {
                onChange("__auto_translate__");
                setOpen(false);
              }}
              style={{
                padding: "9px 14px",
                fontSize: "13px",
                color: value === "__auto_translate__" ? "#a855f7" : "#e4e4e7",
                cursor: "pointer",
                backgroundColor: value === "__auto_translate__" ? "rgba(168, 85, 247, 0.1)" : "transparent",
                borderBottom: "1px solid rgba(255, 255, 255, 0.08)",
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
              }}
            >
              <span>{autoTranslateLabel}</span>
              {value === "__auto_translate__" && <Check size={14} color="#a855f7" />}
            </div>
          )}

          {tracks.map((track) => {
            const isSelected = track.id === value;
            return (
              <div
                key={track.id}
                onClick={() => {
                  onChange(track.id);
                  setOpen(false);
                }}
                style={{
                  padding: "9px 14px",
                  fontSize: "13px",
                  color: isSelected ? "#a855f7" : "#f4f4f5",
                  cursor: "pointer",
                  backgroundColor: isSelected ? "rgba(168, 85, 247, 0.1)" : "transparent",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                }}
              >
                <span>
                  {track.name} {track.isAutoGenerated ? " (Auto)" : ""}
                </span>
                {isSelected && <Check size={14} color="#a855f7" />}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

export const SelectSubtitlesModal: React.FC<SelectSubtitlesModalProps> = ({
  isOpen,
  onClose,
  videoTitle,
  availableTracks,
  currentTrackId,
  secondaryTrackId,
  offset,
  onOffsetChange,
  autoPause,
  onAutoPauseChange,
  fontSize,
  onFontSizeChange,
  showFurigana = true,
  onFuriganaChange,
  onSelectTrack,
  onSelectSecondaryTrack,
  onCustomSubtitleLoaded,
}) => {
  const { t } = useTranslation();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [isDragOver, setIsDragOver] = useState(false);

  if (!isOpen) return null;

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    try {
      const parsed = await readSubtitleFile(file);
      const result = parsedToSubtitleFetchResult(parsed);
      onCustomSubtitleLoaded(result);

      if (!secondaryTrackId && availableTracks.length > 0) {
        const nonJaTrack = availableTracks.find((t) => !t.languageCode.startsWith("ja"));
        if (nonJaTrack) {
          void onSelectSecondaryTrack(nonJaTrack);
        }
      }
      onClose();
    } catch (err) {
      console.error("Failed to parse local subtitle file:", err);
      alert("Failed to parse subtitle file. Supported formats: .srt, .vtt, .ass, .ttml");
    }
  };

  const handleDrop = async (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragOver(false);
    const file = e.dataTransfer.files?.[0];
    if (!file) return;

    try {
      const parsed = await readSubtitleFile(file);
      const result = parsedToSubtitleFetchResult(parsed);
      onCustomSubtitleLoaded(result);

      if (!secondaryTrackId && availableTracks.length > 0) {
        const nonJaTrack = availableTracks.find((t) => !t.languageCode.startsWith("ja"));
        if (nonJaTrack) {
          void onSelectSecondaryTrack(nonJaTrack);
        }
      }
      onClose();
    } catch (err) {
      console.error("Failed to parse local subtitle file:", err);
      alert("Failed to parse subtitle file. Supported formats: .srt, .vtt, .ass, .ttml");
    }
  };

  const handlePrimaryTrackChange = (trackId: string) => {
    const track = availableTracks.find((t) => t.id === trackId);
    if (track) {
      void onSelectTrack(track);
    }
  };

  const handleSecondaryTrackChange = (trackId: string) => {
    if (!trackId) {
      void onSelectSecondaryTrack(null);
    } else if (trackId === "__auto_translate__") {
      void onSelectSecondaryTrack({
        id: "__auto_translate__",
        name: "Auto-translate",
        languageCode: "auto",
      });
    } else {
      const track = availableTracks.find((t) => t.id === trackId);
      if (track) {
        void onSelectSecondaryTrack(track);
      }
    }
  };

  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        backgroundColor: "rgba(0, 0, 0, 0.75)",
        backdropFilter: "blur(8px)",
        zIndex: 2147483647,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "20px",
        pointerEvents: "auto",
        fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      }}
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div
        style={{
          width: "100%",
          maxWidth: "480px",
          maxHeight: "calc(100vh - 32px)",
          backgroundColor: "#111114",
          border: "1px solid rgba(255, 255, 255, 0.14)",
          borderRadius: "16px",
          boxShadow: "0 24px 60px rgba(0, 0, 0, 0.9)",
          overflow: "hidden",
          display: "flex",
          flexDirection: "column",
          color: "#f4f4f5",
        }}
      >
        {/* Header */}
        <div
          style={{
            padding: "16px 20px",
            borderBottom: "1px solid rgba(255, 255, 255, 0.08)",
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            backgroundColor: "#18181c",
            flexShrink: 0,
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
            <Subtitles size={18} color="#c084fc" />
            <div>
              <h2 style={{ margin: 0, fontSize: "15px", fontWeight: 700, color: "#fff" }}>
                {t("sub_modal_title") || "Select Subtitles"}
              </h2>
              <div
                style={{
                  fontSize: "11px",
                  color: "#a1a1aa",
                  maxWidth: "340px",
                  overflow: "hidden",
                  textOverflow: "ellipsis",
                  whiteSpace: "nowrap",
                }}
              >
                {videoTitle || "Video Subtitles"}
              </div>
            </div>
          </div>
          <button
            onClick={onClose}
            style={{
              background: "transparent",
              border: "none",
              color: "#a1a1aa",
              cursor: "pointer",
              padding: "4px",
              borderRadius: "6px",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <X size={18} />
          </button>
        </div>

        {/* Content Body */}
        <div style={{ padding: "20px", overflowY: "auto", flex: 1, display: "flex", flexDirection: "column", gap: "16px" }}>
          {/* Custom Subtitle Upload Dropzone */}
          <div
            onDragOver={(e) => {
              e.preventDefault();
              e.stopPropagation();
              setIsDragOver(true);
            }}
            onDragLeave={(e) => {
              e.preventDefault();
              e.stopPropagation();
              setIsDragOver(false);
            }}
            onDrop={handleDrop}
            onClick={() => fileInputRef.current?.click()}
            style={{
              marginBottom: "18px",
              padding: "14px 16px",
              borderRadius: "10px",
              border: isDragOver ? "2px dashed #c084fc" : "1.5px dashed rgba(192, 132, 252, 0.4)",
              backgroundColor: isDragOver ? "rgba(168, 85, 247, 0.18)" : "rgba(24, 24, 28, 0.75)",
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              cursor: "pointer",
              transition: "all 0.15s ease",
            }}
          >
            <input
              type="file"
              ref={fileInputRef}
              onChange={handleFileChange}
              accept=".srt,.vtt,.ass,.ttml,.json,.txt"
              style={{ display: "none" }}
            />
            <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
              <FolderOpen size={22} color="#c084fc" />
              <div>
                <div style={{ fontSize: "13px", fontWeight: 700, color: "#fff" }}>
                  Load Custom Japanese Subtitles
                </div>
                <div style={{ fontSize: "11px", color: "#a1a1aa", marginTop: "2px" }}>
                  Drag & drop or click to upload .srt, .vtt, .ass file
                </div>
              </div>
            </div>
            <button
              type="button"
              style={{
                fontSize: "11px",
                fontWeight: 700,
                padding: "6px 12px",
                borderRadius: "6px",
                backgroundColor: "rgba(168, 85, 247, 0.25)",
                border: "1px solid rgba(168, 85, 247, 0.4)",
                color: "#c084fc",
                cursor: "pointer",
                whiteSpace: "nowrap",
              }}
            >
              Browse
            </button>
          </div>
          {/* Primary Track (Japanese Target) */}
          <CustomTrackDropdown
            label={t("sub_modal_primary_track")}
            labelColor="#c084fc"
            value={currentTrackId || ""}
            onChange={handlePrimaryTrackChange}
            tracks={availableTracks}
            emptyLabel={t("sub_modal_no_track")}
          />

          {/* Secondary Track (Bilingual Translation) */}
          <CustomTrackDropdown
            label={t("sub_modal_secondary_track")}
            labelColor="#60a5fa"
            value={secondaryTrackId || ""}
            onChange={handleSecondaryTrackChange}
            tracks={availableTracks}
            allowEmpty
            emptyLabel={t("sub_modal_disabled_ja_only")}
            allowAutoTranslate
            autoTranslateLabel={t("sub_modal_auto_translate")}
          />

          {/* Offset Controls */}
          <div style={{ marginTop: "16px", padding: "14px", backgroundColor: "#18181c", borderRadius: "10px" }}>
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "8px" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "6px", fontSize: "12px", color: "#a1a1aa" }}>
                <Clock size={14} />
                <span>{t("sub_modal_sync_offset")}</span>
              </div>
              <span style={{ fontSize: "13px", fontWeight: 700, color: offset === 0 ? "#a1a1aa" : "#a855f7" }}>
                {offset > 0 ? `+${offset.toFixed(1)}s` : `${offset.toFixed(1)}s`}
              </span>
            </div>
            <div style={{ display: "flex", gap: "6px" }}>
              <button
                type="button"
                onClick={() => onOffsetChange(offset - 0.5)}
                style={{ flex: 1, padding: "6px", borderRadius: "6px", background: "#27272a", border: "none", color: "#fff", cursor: "pointer", fontSize: "11px" }}
              >
                -500ms
              </button>
              <button
                type="button"
                onClick={() => onOffsetChange(offset - 0.1)}
                style={{ flex: 1, padding: "6px", borderRadius: "6px", background: "#27272a", border: "none", color: "#fff", cursor: "pointer", fontSize: "11px" }}
              >
                -100ms
              </button>
              <button
                type="button"
                onClick={() => onOffsetChange(0)}
                style={{ flex: 1, padding: "6px", borderRadius: "6px", background: "#27272a", border: "none", color: "#fff", cursor: "pointer", fontSize: "11px" }}
              >
                {t("sub_modal_reset")}
              </button>
              <button
                type="button"
                onClick={() => onOffsetChange(offset + 0.1)}
                style={{ flex: 1, padding: "6px", borderRadius: "6px", background: "#27272a", border: "none", color: "#fff", cursor: "pointer", fontSize: "11px" }}
              >
                +100ms
              </button>
              <button
                type="button"
                onClick={() => onOffsetChange(offset + 0.5)}
                style={{ flex: 1, padding: "6px", borderRadius: "6px", background: "#27272a", border: "none", color: "#fff", cursor: "pointer", fontSize: "11px" }}
              >
                +500ms
              </button>
            </div>
          </div>

          {/* Immersion Settings (Font Size & Auto-Pause) */}
          <div style={{ marginTop: "14px", display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px" }}>
            <div style={{ padding: "12px", backgroundColor: "#18181c", borderRadius: "10px" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "6px", fontSize: "11px", color: "#a1a1aa", marginBottom: "6px" }}>
                <Type size={13} />
                <span>{t("sub_modal_font_size")}: {fontSize}px</span>
              </div>
              <input
                type="range"
                min="18"
                max="38"
                value={fontSize}
                onChange={(e) => onFontSizeChange(Number(e.target.value))}
                style={{ width: "100%", accentColor: "#a855f7" }}
              />
            </div>

            <div
              onClick={() => onAutoPauseChange(!autoPause)}
              style={{
                padding: "12px",
                backgroundColor: autoPause ? "rgba(168, 85, 247, 0.15)" : "#18181c",
                border: autoPause ? "1px solid #a855f7" : "1px solid transparent",
                borderRadius: "10px",
                cursor: "pointer",
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                transition: "all 0.15s",
              }}
            >
              <div>
                <div style={{ fontSize: "12px", fontWeight: 600, color: autoPause ? "#a855f7" : "#fff" }}>
                  {t("sub_modal_autopause")}
                </div>
                <div style={{ fontSize: "10px", color: "#a1a1aa" }}>{t("sub_modal_autopause_desc")}</div>
              </div>
              <input
                type="checkbox"
                checked={autoPause}
                readOnly
                style={{ accentColor: "#a855f7", pointerEvents: "none" }}
              />
            </div>
          </div>

          <div
            onClick={() => onFuriganaChange && onFuriganaChange(!showFurigana)}
            style={{
              marginTop: "10px",
              padding: "12px",
              backgroundColor: showFurigana ? "rgba(168, 85, 247, 0.15)" : "#18181c",
              border: showFurigana ? "1px solid #a855f7" : "1px solid transparent",
              borderRadius: "10px",
              cursor: "pointer",
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              transition: "all 0.15s",
            }}
          >
            <div>
              <div style={{ fontSize: "12px", fontWeight: 600, color: showFurigana ? "#a855f7" : "#fff" }}>
                {t("sub_modal_furigana")}
              </div>
              <div style={{ fontSize: "10px", color: "#a1a1aa" }}>{t("sub_modal_furigana_desc")}</div>
            </div>
            <input
              type="checkbox"
              checked={showFurigana}
              readOnly
              style={{ accentColor: "#a855f7", pointerEvents: "none" }}
            />
          </div>

          {/* Local File Picker Button */}
          <div style={{ marginTop: "16px" }}>
            <input
              type="file"
              ref={fileInputRef}
              accept=".srt,.vtt,.ass,.ssa"
              style={{ display: "none" }}
              onChange={handleFileChange}
            />
            <button
              type="button"
              onClick={() => fileInputRef.current?.click()}
              style={{
                width: "100%",
                padding: "12px",
                borderRadius: "10px",
                backgroundColor: "rgba(255, 255, 255, 0.05)",
                border: "1px dashed rgba(255, 255, 255, 0.2)",
                color: "#f4f4f5",
                fontSize: "13px",
                fontWeight: 600,
                cursor: "pointer",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                gap: "8px",
                transition: "all 0.2s ease",
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.backgroundColor = "rgba(168, 85, 247, 0.1)";
                e.currentTarget.style.borderColor = "#a855f7";
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.backgroundColor = "rgba(255, 255, 255, 0.05)";
                e.currentTarget.style.borderColor = "rgba(255, 255, 255, 0.2)";
              }}
            >
              <FolderOpen size={16} color="#c084fc" />
              <span>{t("sub_modal_btn_open_files")}</span>
            </button>
          </div>
        </div>

        {/* Footer */}
        <div
          style={{
            padding: "12px 20px",
            backgroundColor: "#141418",
            borderTop: "1px solid rgba(255, 255, 255, 0.08)",
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            fontSize: "11px",
            color: "#71717a",
          }}
        >
          <span>{t("sub_modal_tip")}</span>
          <button
            type="button"
            onClick={onClose}
            style={{
              padding: "6px 16px",
              borderRadius: "6px",
              backgroundColor: "#a855f7",
              border: "none",
              color: "#fff",
              fontSize: "12px",
              fontWeight: 600,
              cursor: "pointer",
            }}
          >
            {t("sub_modal_done")}
          </button>
        </div>
      </div>
    </div>
  );
};
