// ── Subtitles ───────────────────────────────────────────────────────────────

export interface SubtitleSegment {
  text: string;
  start: number;
  duration: number;
  words?: SubtitleWordTiming[];
  append?: boolean;
}

export interface SubtitleWordTiming {
  text: string;
  start: number;
  duration: number;
}

export interface SubtitleRequest {
  video_url: string;
  language?: string;
}

export interface SubtitleResponse {
  video_id: string;
  language: string;
  track_name?: string;
  is_auto_generated?: boolean;
  segments: SubtitleSegment[];
  full_text: string;
}

// ── YouTube Caption Tracks ──────────────────────────────────────────────────

export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name: string;
  kind: string;
  isAutoGenerated: boolean;
}

export interface SubtitleFetchResult {
  videoId: string;
  language: string;
  segments: SubtitleSegment[];
  fullText: string;
  trackName: string;
  isAutoGenerated: boolean;
  source?:
    | "player"
    | "transcript_panel"
    | "backend"
    | "local_file"
    | "text_track";
  offset?: number;
}
