/**
 * Generic Video Player — Content Script Overlay
 *
 * Universal support for any HTML5 <video> page.
 * Activates on all URLs except Netflix and YouTube (which have dedicated scripts).
 *
 * Features:
 *  - Disabled by default; user must click the floating 発 button to enable per-site.
 *  - Per-origin opt-in persisted via chrome.storage.local.
 *  - Reads <track kind="subtitles|captions"> elements from the <video> for available tracks.
 *  - Accepts drag & drop .srt/.vtt/.ass files for custom subtitles.
 *  - Draggable floating pill button, position persisted in sessionStorage.
 */

import React, { useEffect, useState, useRef, useCallback } from "react";
import type { SubtitleSegment, SubtitleFetchResult } from "~lib/utils/types";
import { SubtitleOverlay } from "~components/subtitle-overlay";
import { SelectSubtitlesModal, type SubtitleTrackOption } from "~components/select-subtitles-modal";
import { useSettingsStore } from "~lib/utils/settings";
import { useTranslation } from "~lib/locales";
import { containsJapanese } from "~lib/utils/japanese";
import { parseSubtitleContent } from "~lib/services/subtitle-parsers";
import { findSmartCue, buildSmartCues } from "~lib/services/smart-cue";
import { observePrimaryVideo, subscribeToVideoTime } from "~lib/services/video-runtime";

// ── Helpers ───────────────────────────────────────────────────────────────────

const STORAGE_KEY_PREFIX = "hk_generic_enabled_";
const FAB_POS_KEY = "hk_fab_pos";
const GENERIC_STYLE_ID = "hakkutsu-generic-global-style";

function injectGenericGlobalStyle(hideNative: boolean): void {
  let styleEl = document.getElementById(GENERIC_STYLE_ID) as HTMLStyleElement | null;
  if (!styleEl) {
    if (!hideNative) return;
    styleEl = document.createElement("style");
    styleEl.id = GENERIC_STYLE_ID;
    document.head.appendChild(styleEl);
  }

  styleEl.textContent = hideNative
    ? `
      /* Cleanly hide raw player subtitles when Hakkutsu is active */
      .jw-text-track-display,
      .vjs-text-track-display,
      .shaka-text-container,
      .art-subtitles,
      .plyr__captions,
      .subtitle-container:not(#hakkutsu-generic-subtitles-host *):not(.hk-sub__container *),
      .video-js .vjs-text-track-display,
      [class*="subtitle-text" i]:not(#hakkutsu-generic-subtitles-host *):not(.hk-sub__container *),
      [class*="caption-text" i]:not(#hakkutsu-generic-subtitles-host *):not(.hk-sub__container *),
      [class*="timedtext" i]:not(#hakkutsu-generic-subtitles-host *):not(.hk-sub__container *),
      [class*="player-subtitle" i]:not(#hakkutsu-generic-subtitles-host *):not(.hk-sub__container *),
      [class*="subtitle-layer" i]:not(#hakkutsu-generic-subtitles-host *):not(.hk-sub__container *),
      [class*="subtitles-overlay" i]:not(#hakkutsu-generic-subtitles-host *):not(.hk-sub__container *),
      video::cue {
        opacity: 0 !important;
        color: transparent !important;
        text-shadow: none !important;
        background: transparent !important;
      }
    `
    : "";
}

function getSiteKeys(): string[] {
  const keys = [STORAGE_KEY_PREFIX + location.origin];
  try {
    if (window.top && window.top.location.origin) {
      const topKey = STORAGE_KEY_PREFIX + window.top.location.origin;
      if (!keys.includes(topKey)) keys.push(topKey);
    }
  } catch {}
  return keys;
}

async function isSiteEnabled(): Promise<boolean> {
  try {
    const keys = getSiteKeys();
    const result = await chrome.storage.local.get(keys);
    return keys.some((k) => result[k] === true);
  } catch {
    return false;
  }
}

async function setSiteEnabled(enabled: boolean): Promise<void> {
  try {
    const keys = getSiteKeys();
    const updateObj: Record<string, boolean> = {};
    for (const k of keys) {
      updateObj[k] = enabled;
    }
    await chrome.storage.local.set(updateObj);
  } catch {}
}

function loadFabPosition(): { right: number; bottom: number } | null {
  try {
    const raw = sessionStorage.getItem(FAB_POS_KEY);
    if (raw) return JSON.parse(raw);
  } catch {}
  return null;
}

function saveFabPosition(right: number, bottom: number): void {
  try {
    sessionStorage.setItem(FAB_POS_KEY, JSON.stringify({ right, bottom }));
  } catch {}
}

/** Read <track> elements from a <video> and return SubtitleTrackOption[] */
function readVideoTrackElements(video: HTMLVideoElement): SubtitleTrackOption[] {
  const options = new Map<string, SubtitleTrackOption>();
  const trackId = (language: string, label: string) =>
    `track:${language || "und"}:${label || "unlabelled"}`.toLowerCase();

  // Read from the TextTrack API
  for (let i = 0; i < video.textTracks.length; i++) {
    const tt = video.textTracks[i];
    if (tt.kind === "chapters" || tt.kind === "descriptions") continue;
    const id = trackId(tt.language, tt.label);
    options.set(id, {
      id,
      name: tt.label || tt.language || `Track ${i + 1}`,
      languageCode: tt.language || "und",
      isAutoGenerated: false,
    });
  }

  // Also scan <track> DOM elements for src URLs (may have URLs not yet loaded)
  const trackEls = video.querySelectorAll<HTMLTrackElement>("track[src]");
  trackEls.forEach((el) => {
    const kind = el.kind;
    if (kind === "chapters" || kind === "descriptions") return;
    const lang = el.srclang || "und";
    const label = el.label || lang;
    const id = trackId(lang, label);
    const existing = options.get(id);
    options.set(id, {
      ...existing,
      id,
      name: label,
      languageCode: lang,
      url: el.src,
      isAutoGenerated: false,
    });
  });

  return Array.from(options.values());
}

/** Fetch a subtitle track from a URL, with background-script fallback */
async function fetchTrackContent(track: SubtitleTrackOption): Promise<SubtitleSegment[]> {
  if (!track.url) return [];

  let content = "";
  try {
    const res = await fetch(track.url);
    if (res.ok) content = await res.text();
  } catch {}

  if (!content) {
    try {
      const bgRes: any = await chrome.runtime.sendMessage({
        type: "FETCH_TIMEDTEXT_URL",
        payload: { url: track.url },
      });
      if (bgRes?.payload?.success && bgRes?.payload?.text) content = bgRes.payload.text;
    } catch {}
  }

  if (!content) return [];

  const parsed = parseSubtitleContent(content, track.name || track.url);
  return buildSmartCues(parsed.segments, false);
}

// ── Draggable FAB ─────────────────────────────────────────────────────────────

function DraggableFab({
  isEnabled,
  onToggle,
  onOpenModal,
}: {
  isEnabled: boolean;
  onToggle: () => void;
  onOpenModal: () => void;
}) {
  const { t } = useTranslation();
  const defaultPos = loadFabPosition() || { right: 24, bottom: 24 };
  const [pos, setPos] = useState(defaultPos);
  const [isDragging, setIsDragging] = useState(false);
  const [showHoverMenu, setShowHoverMenu] = useState(false);

  const dragStartRef = useRef<{ pointerX: number; pointerY: number; startRight: number; startBottom: number } | null>(null);
  const hideTimeoutRef = useRef<number | null>(null);

  const handlePointerDown = (e: React.PointerEvent) => {
    e.preventDefault();
    e.stopPropagation();

    dragStartRef.current = {
      pointerX: e.clientX,
      pointerY: e.clientY,
      startRight: pos.right,
      startBottom: pos.bottom,
    };

    const handlePointerMove = (moveEvent: PointerEvent) => {
      if (!dragStartRef.current) return;
      const dx = moveEvent.clientX - dragStartRef.current.pointerX;
      const dy = moveEvent.clientY - dragStartRef.current.pointerY;

      if (Math.abs(dx) > 4 || Math.abs(dy) > 4) {
        setIsDragging(true);
      }

      const newRight = Math.max(4, dragStartRef.current.startRight - dx);
      const newBottom = Math.max(4, dragStartRef.current.startBottom - dy);
      setPos({ right: newRight, bottom: newBottom });
      saveFabPosition(newRight, newBottom);
    };

    const handlePointerUp = (upEvent: PointerEvent) => {
      window.removeEventListener("pointermove", handlePointerMove);
      window.removeEventListener("pointerup", handlePointerUp);

      if (dragStartRef.current) {
        const dx = upEvent.clientX - dragStartRef.current.pointerX;
        const dy = upEvent.clientY - dragStartRef.current.pointerY;

        if (Math.hypot(dx, dy) <= 5) {
          onToggle();
        }
      }
      setIsDragging(false);
      dragStartRef.current = null;
    };

    window.addEventListener("pointermove", handlePointerMove);
    window.addEventListener("pointerup", handlePointerUp);
  };

  const handleMouseEnter = () => {
    if (hideTimeoutRef.current) clearTimeout(hideTimeoutRef.current);
    setShowHoverMenu(true);
  };

  const handleMouseLeave = () => {
    hideTimeoutRef.current = window.setTimeout(() => {
      setShowHoverMenu(false);
    }, 280);
  };

  return (
    <div
      style={{
        position: "fixed",
        right: `${pos.right}px`,
        bottom: `${pos.bottom}px`,
        zIndex: 2147483647,
        pointerEvents: "auto",
      }}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
    >
      <button
        onPointerDown={handlePointerDown}
        title={isEnabled ? "Hakkutsu active — click to toggle" : "Click to enable Hakkutsu subtitles"}
        style={{
          width: "44px",
          height: "44px",
          borderRadius: "50%",
          background: isEnabled ? "rgba(20, 20, 26, 0.88)" : "rgba(30, 30, 35, 0.7)",
          backdropFilter: "blur(12px)",
          WebkitBackdropFilter: "blur(12px)",
          border: isEnabled ? "1.5px solid rgba(192, 132, 252, 0.6)" : "1.5px solid rgba(255, 255, 255, 0.2)",
          boxShadow: isDragging
            ? "0 10px 28px rgba(168, 85, 247, 0.5), 0 0 0 2px rgba(192, 132, 252, 0.8)"
            : "0 6px 20px rgba(0, 0, 0, 0.6), 0 0 12px rgba(168, 85, 247, 0.2)",
          color: "#fff",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          cursor: isDragging ? "grabbing" : "grab",
          userSelect: "none",
          touchAction: "none",
          transition: isDragging ? "none" : "transform 0.15s ease, border-color 0.15s ease, box-shadow 0.15s ease",
          transform: isDragging ? "scale(1.1)" : "scale(1)",
        }}
      >
        <span
          style={{
            color: isEnabled ? "#c084fc" : "#a1a1aa",
            fontWeight: 900,
            fontSize: "18px",
            lineHeight: 1,
            pointerEvents: "none",
          }}
        >
          発
        </span>
      </button>

      {showHoverMenu && !isDragging && (
        <div
          style={{
            position: "absolute",
            bottom: "52px",
            right: "0",
            width: "270px",
            background: "rgba(18, 18, 22, 0.96)",
            WebkitBackdropFilter: "blur(16px)",
            border: "1px solid rgba(255, 255, 255, 0.14)",
            borderRadius: "12px",
            boxShadow: "0 16px 36px rgba(0,0,0,0.85)",
            color: "#f4f4f5",
            fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
            zIndex: 2147483647,
            pointerEvents: "auto",
          }}
          onMouseEnter={() => {
            if (hideTimeoutRef.current) clearTimeout(hideTimeoutRef.current);
          }}
          onMouseLeave={handleMouseLeave}
        >
          <div style={{ padding: "10px 14px 8px", borderBottom: "1px solid rgba(255,255,255,0.12)", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "8px", fontWeight: 700, fontSize: "14px", color: "#fff", whiteSpace: "nowrap" }}>
              <span style={{ color: "#c084fc", fontWeight: 900, fontSize: "16px" }}>発</span>
              <span>{t("shortcut_manual_title")}</span>
            </div>
            <button
              onClick={(e) => {
                e.stopPropagation();
                setShowHoverMenu(false);
                onOpenModal();
              }}
              style={{ fontSize: "10px", fontWeight: 700, padding: "3px 8px", borderRadius: "6px", background: "rgba(168,85,247,0.25)", border: "1px solid rgba(168,85,247,0.4)", color: "#c084fc", cursor: "pointer" }}
            >
              {t("shortcut_btn_settings")}
            </button>
          </div>

          <div style={{ padding: "10px 14px 12px", display: "flex", flexDirection: "column", gap: "8px", fontSize: "12px" }}>
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
              <span style={{ color: "#a1a1aa" }}>{t("shortcut_seek_cue")}</span>
              <div style={{ display: "flex", gap: "4px" }}>
                <kbd style={{ padding: "2px 6px", borderRadius: "4px", background: "rgba(255,255,255,0.15)", color: "#fff", fontFamily: "monospace", fontSize: "11px", fontWeight: 700 }}>A</kbd>
                <kbd style={{ padding: "2px 6px", borderRadius: "4px", background: "rgba(255,255,255,0.15)", color: "#fff", fontFamily: "monospace", fontSize: "11px", fontWeight: 700 }}>D</kbd>
              </div>
            </div>

            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
              <span style={{ color: "#a1a1aa" }}>{t("shortcut_toggle_autopause")}</span>
              <kbd style={{ padding: "2px 6px", borderRadius: "4px", background: "rgba(255,255,255,0.15)", color: "#fff", fontFamily: "monospace", fontSize: "11px", fontWeight: 700 }}>E</kbd>
            </div>

            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
              <span style={{ color: "#a1a1aa" }}>{t("shortcut_toggle_furigana")}</span>
              <div style={{ display: "flex", gap: "4px" }}>
                <kbd style={{ padding: "2px 6px", borderRadius: "4px", background: "rgba(255,255,255,0.15)", color: "#fff", fontFamily: "monospace", fontSize: "11px", fontWeight: 700 }}>F</kbd>
                <kbd style={{ padding: "2px 6px", borderRadius: "4px", background: "rgba(255,255,255,0.15)", color: "#fff", fontFamily: "monospace", fontSize: "11px", fontWeight: 700 }}>W</kbd>
              </div>
            </div>

            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
              <span style={{ color: "#a1a1aa" }}>{t("shortcut_toggle_translation")}</span>
              <kbd style={{ padding: "2px 6px", borderRadius: "4px", background: "rgba(255,255,255,0.15)", color: "#fff", fontFamily: "monospace", fontSize: "11px", fontWeight: 700 }}>V</kbd>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// ── Main Component ────────────────────────────────────────────────────────────

export default function GenericSubtitlesOverlay() {
  if (
    typeof window !== "undefined" &&
    (location.hostname.includes("netflix.com") || location.hostname.includes("youtube.com"))
  ) {
    return null;
  }

  const { settings, updateSettings } = useSettingsStore();

  // Per-site enable state — starts false until we check storage
  const [siteEnabled, setSiteEnabled_] = useState(false);
  const [siteChecked, setSiteChecked] = useState(false);
  const [hasVideo, setHasVideo] = useState(false);

  const [isEnabled, setIsEnabled] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [availableTracks, setAvailableTracks] = useState<SubtitleTrackOption[]>([]);
  const [currentTrackId, setCurrentTrackId] = useState<string>("");
  const [secondaryTrackId, setSecondaryTrackId] = useState<string>("__auto_translate__");

  const [subtitleData, setSubtitleData] = useState<SubtitleFetchResult | null>(null);
  const [secondaryData, setSecondaryData] = useState<SubtitleFetchResult | null>(null);
  const [currentSegment, setCurrentSegment] = useState<SubtitleSegment | null>(null);
  const [secondarySegment, setSecondarySegment] = useState<SubtitleSegment | null>(null);
  const [offset, setOffset] = useState(settings.subtitlesOffset || 0);

  const [videoEl, setVideoEl] = useState<HTMLVideoElement | null>(null);
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const currentUrlRef = useRef(window.location.href);
  const hasActiveTextTrackRef = useRef(false);
  const lastDomTextRef = useRef("");

  // ── Inject CSS to hide raw player subtitles ─────────────────────────────────

  useEffect(() => {
    injectGenericGlobalStyle(isEnabled);
    return () => injectGenericGlobalStyle(false);
  }, [isEnabled]);

  // ── Helper to find DOM subtitle text from third-party players (scoped & throttled) ──
  const lastDomSearchTimeRef = useRef(0);
  const findSubtitleText = useCallback((): string => {
    const now = Date.now();
    if (now - lastDomSearchTimeRef.current < 400) {
      return lastDomTextRef.current;
    }
    lastDomSearchTimeRef.current = now;

    const selectors = [
      ".jw-text-track-display",
      ".vjs-text-track-display",
      ".shaka-text-container",
      ".art-subtitles",
      ".plyr__captions",
      ".subtitle-container",
      ".video-js .vjs-text-track-display",
      "[class*='subtitle-text' i]",
      "[class*='caption-text' i]",
      "[class*='timedtext' i]",
      "[class*='player-subtitle' i]",
      "[class*='subtitle-layer' i]",
      "[class*='subtitles-overlay' i]",
    ];

    let fallbackText = "";
    const container = videoRef.current?.parentElement || document.body;

    for (const sel of selectors) {
      const els = container.querySelectorAll(sel);
      for (let i = 0; i < els.length; i++) {
        const el = els[i];
        if (
          el.closest("#hakkutsu-generic-subtitles-host") ||
          el.closest(".hk-sub__container") ||
          el.closest("button") ||
          el.closest("[role='menu']") ||
          el.closest("[role='menuitem']") ||
          el.closest("[role='button']") ||
          el.closest("[class*='menu' i]") ||
          el.closest("[class*='control' i]") ||
          el.closest("[class*='select' i]") ||
          el.closest("[class*='dropdown' i]") ||
          el.closest("[class*='option' i]")
        ) {
          continue;
        }

        const spans = el.querySelectorAll("span, div, p");
        let text = "";
        if (spans.length > 0) {
          text = Array.from(spans)
            .map((s) => s.textContent?.trim() || "")
            .filter(Boolean)
            .join(" ")
            .trim();
        } else {
          text = el.textContent?.trim() || "";
        }

        if (text) {
          if (containsJapanese(text)) return text;
          if (!fallbackText) fallbackText = text;
        }
      }
    }

    return fallbackText;
  }, []);

  // ── Check for a video element on this page ────────────────────────────────

  useEffect(() => {
    return observePrimaryVideo((video) => {
      if (videoRef.current && videoRef.current !== video) {
        setAvailableTracks([]);
        setCurrentTrackId("");
        setSecondaryTrackId("__auto_translate__");
        setSubtitleData(null);
        setSecondaryData(null);
        setCurrentSegment(null);
        setSecondarySegment(null);
        hasActiveTextTrackRef.current = false;
        lastDomTextRef.current = "";
      }
      videoRef.current = video;
      currentUrlRef.current = window.location.href;
      setVideoEl(video);
      setHasVideo(Boolean(video));
    });
  }, []);

  useEffect(() => {
    const placeHost = () => {
      const host = document.getElementById("hakkutsu-generic-subtitles-host");
      if (!host || !videoEl) return;
      const fullscreen = document.fullscreenElement;
      const parent = fullscreen?.contains(videoEl) ? fullscreen : videoEl.parentElement;
      if (parent && host.parentElement !== parent) parent.appendChild(host);
    };
    placeHost();
    document.addEventListener("fullscreenchange", placeHost);
    return () => document.removeEventListener("fullscreenchange", placeHost);
  }, [videoEl]);

  // ── Load per-site opt-in from chrome.storage.local (with cross-frame sync) ──

  useEffect(() => {
    const syncEnabled = () => {
      isSiteEnabled().then((enabled) => {
        setSiteEnabled_(enabled);
        setIsEnabled(enabled && settings.subtitlesEnabled !== false);
        setSiteChecked(true);
      });
    };

    syncEnabled();

    const handleStorageChange = (changes: { [key: string]: chrome.storage.StorageChange }, areaName: string) => {
      if (areaName !== "local") return;
      const keys = getSiteKeys();
      if (keys.some((k) => k in changes)) {
        syncEnabled();
      }
    };

    try {
      chrome.storage.onChanged.addListener(handleStorageChange);
    } catch {}

    return () => {
      try {
        chrome.storage.onChanged.removeListener(handleStorageChange);
      } catch {}
    };
  }, [settings.subtitlesEnabled]);

  // ── Toggle handler ────────────────────────────────────────────────────────

  const handleToggle = useCallback(() => {
    setSiteEnabled_((prev) => {
      const next = !prev;
      setSiteEnabled(next);
      setIsEnabled(next && settings.subtitlesEnabled !== false);
      return next;
    });
  }, [settings.subtitlesEnabled]);

  // ── Read <track> elements when enabled ────────────────────────────────────

  const handleSelectPrimaryTrack = useCallback(async (track: SubtitleTrackOption) => {
    setCurrentTrackId(track.id);
    if (track.fetchResult) {
      setSubtitleData(track.fetchResult);
      return;
    }
    try {
      setLoading(true);
      const segments = await fetchTrackContent(track);
      setSubtitleData({
        videoId: "generic",
        language: track.languageCode,
        trackName: track.name,
        segments,
        fullText: segments.map((s) => s.text).join(" "),
        isAutoGenerated: false,
        source: "player",
      });
      setError(null);
    } catch {
      setError("Failed to load subtitle track");
    } finally {
      setLoading(false);
    }
  }, []);

  const handleSelectSecondaryTrack = useCallback(async (track: SubtitleTrackOption | null) => {
    if (!track) {
      setSecondaryTrackId("");
      setSecondaryData(null);
      return;
    }
    setSecondaryTrackId(track.id);
    if (track.fetchResult) {
      setSecondaryData(track.fetchResult);
      return;
    }
    try {
      const segments = await fetchTrackContent(track);
      setSecondaryData({
        videoId: "generic",
        language: track.languageCode,
        trackName: track.name,
        segments,
        fullText: segments.map((s) => s.text).join(" "),
        isAutoGenerated: false,
        source: "player",
      });
    } catch {}
  }, []);

  useEffect(() => {
    if (!isEnabled || !videoRef.current) return;

    const video = videoRef.current;
    const scan = () => {
      const tracks = readVideoTrackElements(video);
      if (tracks.length > 0) {
        setAvailableTracks((prev) => {
          const map = new Map(prev.map((t) => [t.id, t]));
          for (const t of tracks) {
            if (!map.has(t.id)) map.set(t.id, t);
          }
          return Array.from(map.values());
        });

        if (!currentTrackId) {
          const ja = tracks.find((t) => t.languageCode.startsWith("ja"));
          if (ja) {
            handleSelectPrimaryTrack(ja);
          } else if (tracks.length > 0 && !secondaryTrackId) {
            const nonJa = tracks.find((t) => !t.languageCode.startsWith("ja"));
            if (nonJa) {
              handleSelectSecondaryTrack(nonJa);
            }
          }
        }
      }
    };

    scan();
    const interval = setInterval(scan, 5000);
    return () => {
      clearInterval(interval);
    };
  }, [isEnabled, currentTrackId, secondaryTrackId, handleSelectPrimaryTrack, handleSelectSecondaryTrack]);

  // ── Frame sync loop & Live TextTrack Cue Extraction ─────────────────────

  const getLiveTextTrackCue = useCallback(
    (video: HTMLVideoElement): { primary: SubtitleSegment | null; secondary: SubtitleSegment | null } => {
      if (!video.textTracks || video.textTracks.length === 0) {
        return { primary: null, secondary: null };
      }

      let primaryCue: SubtitleSegment | null = null;
      let secondaryCue: SubtitleSegment | null = null;

      for (let i = 0; i < video.textTracks.length; i++) {
        const tt = video.textTracks[i];
        if (tt.kind === "chapters" || tt.kind === "descriptions") continue;

        // Hide native UI rendering while keeping activeCues firing
        if (tt.mode === "showing" || tt.mode === "disabled") {
          try {
            tt.mode = "hidden";
          } catch {}
        }

        const lang = tt.language || "";
        const label = tt.label || "";
        const trackId = `track:${lang || "und"}:${label || "unlabelled"}`.toLowerCase();
        const isJa = lang.startsWith("ja") || /ja|jp|japanese/i.test(label);

        const isSelectedPrimary = currentTrackId
          ? currentTrackId === trackId || currentTrackId.includes(label) || currentTrackId.includes(lang)
          : isJa;
        const isSelectedSecondary = secondaryTrackId && secondaryTrackId !== "__auto_translate__"
          ? secondaryTrackId === trackId || secondaryTrackId.includes(label) || secondaryTrackId.includes(lang)
          : !isSelectedPrimary && !isJa;

        const activeCues = tt.activeCues;
        if (activeCues && activeCues.length > 0) {
          let text = "";
          let start = 0;
          let end = 0;
          for (let j = 0; j < activeCues.length; j++) {
            const cue = activeCues[j] as any;
            if (cue.text) {
              const cleaned = String(cue.text).replace(/<[^>]*>/g, "").trim();
              if (cleaned) {
                text += (text ? "\n" : "") + cleaned;
                start = cue.startTime;
                end = cue.endTime;
              }
            }
          }
          if (text) {
            const seg: SubtitleSegment = { text, start, duration: Math.max(2, end - start) };
            if (isSelectedPrimary && !primaryCue) {
              primaryCue = seg;
            } else if (isSelectedSecondary && !secondaryCue) {
              secondaryCue = seg;
            } else if (!primaryCue) {
              primaryCue = seg;
            }
          }
        }
      }

      return { primary: primaryCue, secondary: secondaryCue };
    },
    [currentTrackId, secondaryTrackId]
  );

  useEffect(() => {
    if (!isEnabled) {
      setCurrentSegment(null);
      setSecondarySegment(null);
      hasActiveTextTrackRef.current = false;
      lastDomTextRef.current = "";
      return;
    }

    const video = videoEl || videoRef.current || document.querySelector<HTMLVideoElement>("video");
    if (!video) return;

    const syncCues = () => {
      const adjustedTime = video.currentTime - offset;

      if (subtitleData?.segments?.length) {
        setCurrentSegment(findSmartCue(subtitleData.segments, adjustedTime));
      } else {
        const liveCues = getLiveTextTrackCue(video);
        if (liveCues.primary) {
          hasActiveTextTrackRef.current = true;
          setCurrentSegment(liveCues.primary);
        } else if (hasActiveTextTrackRef.current) {
          setCurrentSegment(null);
        } else {
          // DOM subtitle scanning fallback for third-party players (throttled)
          const domText = findSubtitleText();
          if (domText) {
            if (domText !== lastDomTextRef.current) {
              lastDomTextRef.current = domText;
              setCurrentSegment({
                start: adjustedTime,
                duration: 4,
                text: domText,
              });
            }
          } else if (lastDomTextRef.current) {
            lastDomTextRef.current = "";
            setCurrentSegment(null);
          }
        }
      }

      if (secondaryData?.segments?.length) {
        setSecondarySegment(findSmartCue(secondaryData.segments, adjustedTime));
      } else {
        const liveCues = getLiveTextTrackCue(video);
        if (liveCues.secondary) {
          setSecondarySegment(liveCues.secondary);
        } else {
          setSecondarySegment(null);
        }
      }
    };

    return subscribeToVideoTime(video, syncCues);
  }, [isEnabled, subtitleData, secondaryData, offset, videoEl, getLiveTextTrackCue, findSubtitleText]);

  const handleCustomSubtitleLoaded = useCallback((result: SubtitleFetchResult) => {
    const option: SubtitleTrackOption = {
      id: `custom-${Date.now()}`,
      name: result.trackName || "Custom Subtitles",
      languageCode: result.language || "ja",
      fetchResult: result,
    };
    setAvailableTracks((prev) => [option, ...prev]);
    setCurrentTrackId(option.id);
    setSubtitleData(result);
    setIsEnabled(true);
    setError(null);

    if (!secondaryTrackId && availableTracks.length > 0) {
      const nonJaTrack = availableTracks.find((t) => !t.languageCode.startsWith("ja"));
      if (nonJaTrack) {
        handleSelectSecondaryTrack(nonJaTrack);
      }
    }
  }, [secondaryTrackId, availableTracks, handleSelectSecondaryTrack]);

  if (!hasVideo || !siteChecked) return null;
  return (
    <>
      <DraggableFab
        isEnabled={siteEnabled}
        onToggle={handleToggle}
        onOpenModal={() => setIsModalOpen(true)}
      />

      {isEnabled && (
        <>
          <SubtitleOverlay
            isEnabled={isEnabled}
            loading={loading}
            error={error}
            subtitleData={subtitleData}
            currentSegment={currentSegment}
            secondarySegment={secondarySegment}
            videoRef={videoRef}
            currentUrl={currentUrlRef.current}
            availableTracks={availableTracks}
            secondaryTrackId={secondaryTrackId}
            offset={offset}
            onToggleEnabled={handleToggle}
            onOffsetChange={(newOffset) => setOffset(newOffset)}
            onLoadCustomSubtitles={handleCustomSubtitleLoaded}
            onSeekTime={(timeSec) => {
              if (videoRef.current) {
                try {
                  videoRef.current.currentTime = Math.max(0, timeSec);
                } catch {}
              }
            }}
            onSeekToCue={(cue) => {
              if (videoRef.current) {
                try {
                  videoRef.current.currentTime = Math.max(0, cue.start + offset);
                } catch {}
              }
            }}
          />

          <SelectSubtitlesModal
            isOpen={isModalOpen}
            onClose={() => setIsModalOpen(false)}
            videoTitle={document.title}
            availableTracks={availableTracks}
            currentTrackId={currentTrackId}
            secondaryTrackId={secondaryTrackId}
            offset={offset}
            onOffsetChange={(newOffset) => {
              setOffset(newOffset);
              updateSettings({ subtitlesOffset: newOffset });
            }}
            autoPause={settings.subtitlesAutoPause}
            onAutoPauseChange={(ap) => updateSettings({ subtitlesAutoPause: ap })}
            showFurigana={settings.showFurigana !== false}
            onFuriganaChange={(fg) => updateSettings({ showFurigana: fg })}
            fontSize={settings.subtitlesFontSize || 26}
            onFontSizeChange={(size) => updateSettings({ subtitlesFontSize: size })}
            onSelectTrack={handleSelectPrimaryTrack}
            onSelectSecondaryTrack={handleSelectSecondaryTrack}
            onCustomSubtitleLoaded={handleCustomSubtitleLoaded}
          />
        </>
      )}
    </>
  );
}
