/**
 * Generic Video Player — Content Script Overlay
 *
 * Universal support for any HTML5 <video> page.
 * Activates on all URLs except Netflix and YouTube (which have dedicated scripts).
 *
 * Features:
 *  - Disabled by default; user must click the floating 発 button to enable per-site.
 *  - Per-origin opt-in persisted via chrome.storage.local.
 *  - Reads <track kind="subtitles|captions"> elements from the <video> for available tracks.
 *  - Accepts drag & drop .srt/.vtt/.ass files for custom subtitles.
 *  - Draggable floating pill button, position persisted in sessionStorage.
 */

import type { PlasmoCSConfig, PlasmoGetStyle } from "plasmo";
import React, { useEffect, useState, useRef, useCallback } from "react";
import cssText from "data-text:~style.css";
import type { SubtitleSegment, SubtitleFetchResult } from "~lib/types";
import { youtubeSubtitleCss, genericPlayerCss } from "~lib/youtube-subtitle-styles";
import { SubtitleOverlay } from "~components/subtitle-overlay";
import { SelectSubtitlesModal, type SubtitleTrackOption } from "~components/select-subtitles-modal";
import { useSettingsStore } from "~lib/utils/settings";
import { readSubtitleFile, parsedToSubtitleFetchResult } from "~lib/services/subtitle-parsers";
import { findSmartCue, buildSmartCues } from "~lib/services/smart-cue";

export const config: PlasmoCSConfig = {
  matches: ["<all_urls>"],
  exclude_matches: [
    "*://*.netflix.com/*",
    "*://netflix.com/*",
    "*://*.youtube.com/*",
    "*://youtube.com/*",
  ],
  run_at: "document_idle",
};

export const getShadowHostId = () => "hakkutsu-generic-subtitles-host";

export const getStyle: PlasmoGetStyle = () => {
  const style = document.createElement("style");
  style.textContent = cssText + youtubeSubtitleCss + genericPlayerCss;
  return style;
};

// ── Helpers ───────────────────────────────────────────────────────────────────

const STORAGE_KEY_PREFIX = "hk_generic_enabled_";
const FAB_POS_KEY = "hk_fab_pos";

function getSiteKey(): string {
  return STORAGE_KEY_PREFIX + location.origin;
}

async function isSiteEnabled(): Promise<boolean> {
  try {
    const result = await chrome.storage.local.get(getSiteKey());
    return result[getSiteKey()] === true;
  } catch {
    return false;
  }
}

async function setSiteEnabled(enabled: boolean): Promise<void> {
  try {
    await chrome.storage.local.set({ [getSiteKey()]: enabled });
  } catch {}
}

function loadFabPosition(): { right: number; bottom: number } | null {
  try {
    const raw = sessionStorage.getItem(FAB_POS_KEY);
    if (raw) return JSON.parse(raw);
  } catch {}
  return null;
}

function saveFabPosition(right: number, bottom: number): void {
  try {
    sessionStorage.setItem(FAB_POS_KEY, JSON.stringify({ right, bottom }));
  } catch {}
}

/** Read <track> elements from a <video> and return SubtitleTrackOption[] */
function readVideoTrackElements(video: HTMLVideoElement): SubtitleTrackOption[] {
  const options: SubtitleTrackOption[] = [];
  const seen = new Set<string>();

  // Read from the TextTrack API
  for (let i = 0; i < video.textTracks.length; i++) {
    const tt = video.textTracks[i];
    if (tt.kind !== "subtitles" && tt.kind !== "captions") continue;
    const id = `track-${i}-${tt.language}-${tt.label}`;
    if (seen.has(id)) continue;
    seen.add(id);
    options.push({
      id,
      name: tt.label || tt.language || `Track ${i + 1}`,
      languageCode: tt.language || "und",
      isAutoGenerated: false,
    });
  }

  // Also scan <track> DOM elements for src URLs (may have URLs not yet loaded)
  const trackEls = video.querySelectorAll<HTMLTrackElement>("track[src]");
  trackEls.forEach((el, i) => {
    const kind = el.kind;
    if (kind !== "subtitles" && kind !== "captions") return;
    const lang = el.srclang || "und";
    const label = el.label || lang;
    const id = `track-el-${i}-${lang}-${label}`;
    if (seen.has(id)) return;
    seen.add(id);
    options.push({
      id,
      name: label,
      languageCode: lang,
      url: el.src,
      isAutoGenerated: false,
    });
  });

  return options;
}

/** Fetch a subtitle track from a URL, with background-script fallback */
async function fetchTrackContent(track: SubtitleTrackOption): Promise<SubtitleSegment[]> {
  if (!track.url) return [];

  let content = "";
  try {
    const res = await fetch(track.url);
    if (res.ok) content = await res.text();
  } catch {}

  if (!content) {
    try {
      const bgRes: any = await chrome.runtime.sendMessage({
        type: "FETCH_TIMEDTEXT_URL",
        payload: { url: track.url },
      });
      if (bgRes?.payload?.success && bgRes?.payload?.text) content = bgRes.payload.text;
    } catch {}
  }

  if (!content) return [];

  const { parseVtt, parseSrt } = await import("~lib/services/subtitle-parsers") as any;
  const trimmed = content.trim();
  let segments: SubtitleSegment[] = [];
  if (typeof parseVtt === "function" && trimmed.startsWith("WEBVTT")) {
    segments = parseVtt(content);
  } else if (typeof parseSrt === "function" && /^\d+\s*\n\d{2}:\d{2}/.test(trimmed)) {
    segments = parseSrt(content);
  }
  return buildSmartCues(segments, false);
}

// ── Draggable FAB ─────────────────────────────────────────────────────────────

interface FabProps {
  isEnabled: boolean;
  onToggle: () => void;
}

function DraggableFab({ isEnabled, onToggle }: FabProps) {
  const fabRef = useRef<HTMLDivElement>(null);
  const dragState = useRef<{
    startX: number;
    startY: number;
    startRight: number;
    startBottom: number;
  } | null>(null);
  const hasDragged = useRef(false);

  const defaultPos = loadFabPosition() || { right: 24, bottom: 24 };
  const [pos, setPos] = useState(defaultPos);

  const onMouseDown = useCallback(
    (e: React.MouseEvent) => {
      if (e.button !== 0) return;
      e.preventDefault();
      hasDragged.current = false;

      dragState.current = {
        startX: e.clientX,
        startY: e.clientY,
        startRight: pos.right,
        startBottom: pos.bottom,
      };

      const fab = fabRef.current;
      if (fab) fab.classList.add("is-dragging");

      const onMove = (ev: MouseEvent) => {
        if (!dragState.current) return;
        const dx = ev.clientX - dragState.current.startX;
        const dy = ev.clientY - dragState.current.startY;
        if (Math.abs(dx) > 3 || Math.abs(dy) > 3) hasDragged.current = true;

        const newRight = Math.max(4, dragState.current.startRight - dx);
        const newBottom = Math.max(4, dragState.current.startBottom - dy);
        setPos({ right: newRight, bottom: newBottom });
        saveFabPosition(newRight, newBottom);
      };

      const onUp = () => {
        dragState.current = null;
        const fab = fabRef.current;
        if (fab) fab.classList.remove("is-dragging");
        document.removeEventListener("mousemove", onMove);
        document.removeEventListener("mouseup", onUp);
      };

      document.addEventListener("mousemove", onMove);
      document.addEventListener("mouseup", onUp);
    },
    [pos]
  );

  const onClick = useCallback(
    (e: React.MouseEvent) => {
      if (hasDragged.current) {
        e.stopPropagation();
        return;
      }
      onToggle();
    },
    [onToggle]
  );

  return (
    <div
      ref={fabRef}
      className={`hk-generic-fab ${isEnabled ? "is-active" : "is-off"}`}
      style={{ right: pos.right, bottom: pos.bottom }}
      onMouseDown={onMouseDown}
      onClick={onClick}
      title={
        isEnabled
          ? "Hakkutsu active — click to disable"
          : "Click to enable Hakkutsu subtitles on this page"
      }
    >
      <span className="hk-generic-fab__kanji">発</span>
      <span className="hk-generic-fab__label">{isEnabled ? "ON" : "OFF"}</span>
      <span className="hk-generic-fab__dot" />
    </div>
  );
}

// ── Main Component ────────────────────────────────────────────────────────────

export default function GenericSubtitlesOverlay() {
  if (
    typeof window !== "undefined" &&
    (location.hostname.includes("netflix.com") || location.hostname.includes("youtube.com"))
  ) {
    return null;
  }

  const { settings, updateSettings } = useSettingsStore();

  // Per-site enable state — starts false until we check storage
  const [siteEnabled, setSiteEnabled_] = useState(false);
  const [siteChecked, setSiteChecked] = useState(false);
  const [hasVideo, setHasVideo] = useState(false);

  const [isEnabled, setIsEnabled] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [availableTracks, setAvailableTracks] = useState<SubtitleTrackOption[]>([]);
  const [currentTrackId, setCurrentTrackId] = useState<string>("");
  const [secondaryTrackId, setSecondaryTrackId] = useState<string>("");

  const [subtitleData, setSubtitleData] = useState<SubtitleFetchResult | null>(null);
  const [secondaryData, setSecondaryData] = useState<SubtitleFetchResult | null>(null);
  const [currentSegment, setCurrentSegment] = useState<SubtitleSegment | null>(null);
  const [secondarySegment, setSecondarySegment] = useState<SubtitleSegment | null>(null);
  const [offset, setOffset] = useState(settings.subtitlesOffset || 0);

  const videoRef = useRef<HTMLVideoElement | null>(null);
  const rafIdRef = useRef<number | null>(null);
  const currentUrlRef = useRef(window.location.href);

  // ── Check for a video element on this page ────────────────────────────────

  useEffect(() => {
    const checkVideo = () => {
      const vid = document.querySelector<HTMLVideoElement>("video");
      if (vid) {
        videoRef.current = vid;
        setHasVideo(true);
      }
    };
    checkVideo();
    const interval = setInterval(checkVideo, 1500);
    return () => clearInterval(interval);
  }, []);

  // ── Load per-site opt-in from chrome.storage.local ────────────────────────

  useEffect(() => {
    isSiteEnabled().then((enabled) => {
      setSiteEnabled_(enabled);
      setIsEnabled(enabled && settings.subtitlesEnabled !== false);
      setSiteChecked(true);
    });
  }, []);

  // ── Toggle handler ────────────────────────────────────────────────────────

  const handleToggle = useCallback(() => {
    setSiteEnabled_((prev) => {
      const next = !prev;
      setSiteEnabled(next);
      setIsEnabled(next && settings.subtitlesEnabled !== false);
      return next;
    });
  }, [settings.subtitlesEnabled]);

  // ── Read <track> elements when enabled ────────────────────────────────────

  const handleSelectPrimaryTrack = useCallback(async (track: SubtitleTrackOption) => {
    setCurrentTrackId(track.id);
    if (track.fetchResult) {
      setSubtitleData(track.fetchResult);
      return;
    }
    try {
      setLoading(true);
      const segments = await fetchTrackContent(track);
      setSubtitleData({
        videoId: "generic",
        language: track.languageCode,
        trackName: track.name,
        segments,
        fullText: segments.map((s) => s.text).join(" "),
        isAutoGenerated: false,
        source: "player",
      });
      setError(null);
    } catch {
      setError("Failed to load subtitle track");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (!isEnabled || !videoRef.current) return;

    const video = videoRef.current;
    const scan = () => {
      const tracks = readVideoTrackElements(video);
      if (tracks.length > 0) {
        setAvailableTracks((prev) => {
          const map = new Map(prev.map((t) => [t.id, t]));
          for (const t of tracks) {
            if (!map.has(t.id)) map.set(t.id, t);
          }
          return Array.from(map.values());
        });

        if (!currentTrackId) {
          const ja = tracks.find((t) => t.languageCode.startsWith("ja"));
          if (ja) handleSelectPrimaryTrack(ja);
        }
      }
    };

    scan();
    const interval = setInterval(scan, 3000);
    const observer = new MutationObserver(scan);
    observer.observe(video, { childList: true, subtree: true });

    return () => {
      clearInterval(interval);
      observer.disconnect();
    };
  }, [isEnabled, currentTrackId, handleSelectPrimaryTrack]);

  // ── Frame sync loop ───────────────────────────────────────────────────────

  useEffect(() => {
    if (!isEnabled) {
      setCurrentSegment(null);
      setSecondarySegment(null);
      return;
    }

    const video = videoRef.current || document.querySelector<HTMLVideoElement>("video");
    if (!video) return;
    videoRef.current = video;

    const syncCues = () => {
      const adjustedTime = video.currentTime - offset;
      if (subtitleData?.segments?.length) {
        setCurrentSegment(findSmartCue(subtitleData.segments, adjustedTime));
      } else {
        setCurrentSegment(null);
      }
      if (secondaryData?.segments?.length) {
        setSecondarySegment(findSmartCue(secondaryData.segments, adjustedTime));
      } else {
        setSecondarySegment(null);
      }
    };

    syncCues();
    let running = true;
    const tick = () => {
      if (!running) return;
      syncCues();
      rafIdRef.current = requestAnimationFrame(tick);
    };
    rafIdRef.current = requestAnimationFrame(tick);
    video.addEventListener("seeked", syncCues);
    video.addEventListener("timeupdate", syncCues);

    return () => {
      running = false;
      if (rafIdRef.current) cancelAnimationFrame(rafIdRef.current);
      video.removeEventListener("seeked", syncCues);
      video.removeEventListener("timeupdate", syncCues);
    };
  }, [isEnabled, subtitleData, secondaryData, offset]);

  // ── Secondary track & custom subtitle handlers ─────────────────────────────

  const handleSelectSecondaryTrack = useCallback(async (track: SubtitleTrackOption | null) => {
    if (!track) {
      setSecondaryTrackId("");
      setSecondaryData(null);
      return;
    }
    setSecondaryTrackId(track.id);
    if (track.fetchResult) {
      setSecondaryData(track.fetchResult);
      return;
    }
    try {
      const segments = await fetchTrackContent(track);
      setSecondaryData({
        videoId: "generic",
        language: track.languageCode,
        trackName: track.name,
        segments,
        fullText: segments.map((s) => s.text).join(" "),
        isAutoGenerated: false,
        source: "player",
      });
    } catch {}
  }, []);

  const handleCustomSubtitleLoaded = useCallback((result: SubtitleFetchResult) => {
    const option: SubtitleTrackOption = {
      id: `custom-${Date.now()}`,
      name: result.trackName || "Custom Subtitles",
      languageCode: result.language || "ja",
      fetchResult: result,
    };
    setAvailableTracks((prev) => [option, ...prev]);
    setCurrentTrackId(option.id);
    setSubtitleData(result);
  }, []);

  // ── Render ────────────────────────────────────────────────────────────────

  // Don't inject anything if this page has no video element
  if (!hasVideo || !siteChecked) return null;

  return (
    <>
      {/* Draggable enable/disable pill — always visible when a video is detected */}
      <DraggableFab isEnabled={siteEnabled} onToggle={handleToggle} />

      {/* Subtitle overlay and modal — only when user has opted in for this site */}
      {isEnabled && (
        <>
          <SubtitleOverlay
            isEnabled={isEnabled}
            loading={loading}
            error={error}
            subtitleData={subtitleData}
            currentSegment={currentSegment}
            secondarySegment={secondarySegment}
            videoRef={videoRef}
            currentUrl={currentUrlRef.current}
            videoTitle={document.title}
            availableTracks={availableTracks}
            currentTrackId={currentTrackId}
            secondaryTrackId={secondaryTrackId}
            offset={offset}
            onToggleEnabled={handleToggle}
            onOffsetChange={(newOffset) => setOffset(newOffset)}
            onSelectTrack={handleSelectPrimaryTrack}
            onSelectSecondaryTrack={handleSelectSecondaryTrack}
            onLoadCustomSubtitles={handleCustomSubtitleLoaded}
            onOpenModal={() => setIsModalOpen(true)}
            onSeekToCue={(cue) => {
              if (videoRef.current) {
                videoRef.current.currentTime = Math.max(0, cue.start + offset);
              }
            }}
          />

          <SelectSubtitlesModal
            isOpen={isModalOpen}
            onClose={() => setIsModalOpen(false)}
            videoTitle={document.title}
            availableTracks={availableTracks}
            currentTrackId={currentTrackId}
            secondaryTrackId={secondaryTrackId}
            offset={offset}
            onOffsetChange={(newOffset) => {
              setOffset(newOffset);
              updateSettings({ subtitlesOffset: newOffset });
            }}
            autoPause={settings.subtitlesAutoPause}
            onAutoPauseChange={(ap) => updateSettings({ subtitlesAutoPause: ap })}
            showFurigana={settings.showFurigana !== false}
            onFuriganaChange={(fg) => updateSettings({ showFurigana: fg })}
            fontSize={settings.subtitlesFontSize || 26}
            onFontSizeChange={(size) => updateSettings({ subtitlesFontSize: size })}
            onSelectTrack={handleSelectPrimaryTrack}
            onSelectSecondaryTrack={handleSelectSecondaryTrack}
            onCustomSubtitleLoaded={handleCustomSubtitleLoaded}
          />
        </>
      )}
    </>
  );
}
