/**
 * YouTube Page Bridge — runs in YouTube's MAIN world.
 *
 * Adopts ASBPlayer's proven extraction techniques:
 * 1. Inspects #movie_player.getAudioTrack()?.captionTracks with runtime POT tokens.
 * 2. Falls back to Android InnerTube and static player responses when live tracks are unavailable.
 * 3. Prepares srv3 timedtext URLs.
 * 4. Communicates with Hakkutsu's content script via CustomEvents.
 */

export interface HakkutsuYouTubeTrack {
  id: string;
  label: string;
  language: string;
  url: string;
  isAutoGenerated: boolean;
  kind?: string;
}

export interface HakkutsuYouTubeSyncedData {
  videoId: string;
  title: string;
  tracks: HakkutsuYouTubeTrack[];
  error?: string;
}

export function initYouTubePageBridge(): void {
  function bridgeMain() {
    if ((window as any).__HAKKUTSU_YT_BRIDGE_INITIALIZED__) return;
    (window as any).__HAKKUTSU_YT_BRIDGE_INITIALIZED__ = true;

    interface CaptionTrackDef {
      baseUrl?: string;
      url?: string;
      name?: { simpleText?: string; runs?: Array<{ text: string }> };
      displayName?: string;
      languageName?: string;
      languageCode: string;
      vssId?: string;
      kind?: string;
    }

    function pollCondition<T>(fn: () => T | null | undefined | false, timeoutMs: number = 5000, intervalMs: number = 200): Promise<T | null> {
      return new Promise((resolve) => {
        const startTime = Date.now();
        const check = () => {
          try {
            const result = fn();
            if (result) {
              resolve(result);
              return;
            }
          } catch {
            // ignore
          }

          if (Date.now() - startTime >= timeoutMs) {
            resolve(null);
          } else {
            setTimeout(check, intervalMs);
          }
        };
        check();
      });
    }

    const inferVideoId = (): string | undefined => {
      const pathname = window.location.pathname;
      if (pathname) {
        const pathVideoId = /\/(shorts|embed)\/([^/?&#]+)/.exec(pathname)?.[2];
        if (pathVideoId) return pathVideoId;
      }
      const params = new URLSearchParams(window.location.search);
      return params.get("v") ?? undefined;
    };

    const getTrackLabel = (track: CaptionTrackDef): string => {
      return (
        track.name?.simpleText ||
        track.name?.runs?.[0]?.text ||
        track.displayName ||
        track.languageName ||
        track.languageCode ||
        "Unknown Track"
      );
    };

    const prepareTimedTextUrl = (rawUrl: string, client?: string): string => {
      try {
        const url = new URL(rawUrl, window.location.href);
        url.searchParams.set("fmt", "srv3");
        if (!url.searchParams.has("c")) {
          const configuredClient = (window as any).ytcfg?.get?.("INNERTUBE_CLIENT_NAME");
          url.searchParams.set("c", client || (typeof configuredClient === "string" && !/^\d+$/.test(configuredClient) ? configuredClient : "WEB"));
        }
        return url.toString();
      } catch {
        return rawUrl;
      }
    };

    const normalizeTrack = (track: CaptionTrackDef, client?: string): HakkutsuYouTubeTrack | null => {
      const timedTextUrl = track.url || track.baseUrl;
      const language = track.languageCode;
      if (!timedTextUrl || !language) return null;

      const url = prepareTimedTextUrl(timedTextUrl, client);
      const isAutoGenerated = track.kind === "asr" || (track.vssId ? track.vssId.startsWith("a.") : false);

      return {
        id: `${language}-${track.vssId || ""}-${isAutoGenerated ? "auto" : "std"}`,
        label: getTrackLabel(track),
        language,
        url,
        isAutoGenerated,
        kind: track.kind,
      };
    };

    async function tracksFromPlayerAudioTrack(videoId: string): Promise<{ title: string; tracks: HakkutsuYouTubeTrack[] } | null> {
      const result = await pollCondition(() => {
        const player = document.querySelector<any>("#movie_player");
        if (!player) return false;

        const playerVideoId = player.getVideoData?.()?.video_id;
        if (playerVideoId && playerVideoId !== videoId) return false;

        const tracks = player.getAudioTrack?.()?.captionTracks;
        if (Array.isArray(tracks) && tracks.length > 0) {
          const normalized = tracks
            .map((track) => normalizeTrack(track))
            .filter((t): t is HakkutsuYouTubeTrack => t !== null);

          // Static WEB tracks often appear before their runtime token. Wait
          // for usable player URLs rather than returning those too early.
          if (normalized.some((track) => {
            const url = new URL(track.url);
            return url.searchParams.has("pot") || !["WEB", "MWEB"].includes(url.searchParams.get("c") || "WEB");
          })) {
            return {
              title: player.getVideoData?.()?.title || document.title,
              tracks: normalized,
            };
          }
        }
        return false;
      }, 4000);

      if (result) {
        return { title: result.title, tracks: result.tracks };
      }
      return null;
    }

    async function tracksFromAndroidInnerTube(videoId: string): Promise<{ title: string; tracks: HakkutsuYouTubeTrack[] } | null> {
      const controller = new AbortController();
      let timer: ReturnType<typeof setTimeout> | undefined;
      try {
        const ytcfg = (window as any).ytcfg;
        if (typeof ytcfg?.get !== "function") return null;

        const apiKey = ytcfg.get("INNERTUBE_API_KEY");
        if (!apiKey) return null;

        timer = setTimeout(() => controller.abort(), 8000);
        const response = await fetch(`https://${window.location.host}/youtubei/v1/player?key=${apiKey}`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          signal: controller.signal,
          body: JSON.stringify({
            context: {
              client: {
                clientName: "ANDROID",
                clientVersion: "20.10.38",
                hl: ytcfg.get("HL") || "en",
              },
            },
            videoId,
          }),
        });

        if (response.status !== 200) return null;
        const payload = await response.json();
        const title = payload.videoDetails?.title || document.title;
        const captionTracks = payload?.captions?.playerCaptionsTracklistRenderer?.captionTracks;

        if (Array.isArray(captionTracks) && captionTracks.length > 0) {
          const tracks = captionTracks
            .map((track) => normalizeTrack(track, "ANDROID"))
            .filter((t): t is HakkutsuYouTubeTrack => t !== null);
          return { title, tracks };
        }
      } catch (err) {
        console.warn("[Hakkutsu Bridge] Android InnerTube error:", err);
      } finally {
        if (timer !== undefined) clearTimeout(timer);
      }
      return null;
    }

    function tracksFromInitialResponse(videoId: string): { title: string; tracks: HakkutsuYouTubeTrack[] } | null {
      try {
        const player = document.querySelector<any>("#movie_player");
        const playerResponse = player?.getPlayerResponse?.();
        const response = playerResponse?.videoDetails?.videoId === videoId
          ? playerResponse
          : (window as any).ytInitialPlayerResponse;
        if (response?.videoDetails?.videoId !== videoId) return null;
        const captionTracks = response?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
        const title = response?.videoDetails?.title || document.title;

        if (Array.isArray(captionTracks) && captionTracks.length > 0) {
          const tracks = captionTracks
            .map((track) => normalizeTrack(track))
            .filter((t): t is HakkutsuYouTubeTrack => t !== null);
          if (tracks.length > 0) {
            return { title, tracks };
          }
        }
      } catch {
        // ignore
      }
      return null;
    }

    async function discoverTracks(videoId: string): Promise<void> {
      let title = document.title;
      let tracks: HakkutsuYouTubeTrack[] = [];

      // Runtime caption URLs carry the current video's token. Static player
      // responses can list the same tracks without that token.
      const playerResult = await tracksFromPlayerAudioTrack(videoId);
      if (playerResult?.tracks.length) {
        title = playerResult.title;
        tracks = playerResult.tracks;
      }

      // Fallback for players without initialized runtime caption tracks.
      if (tracks.length === 0) {
        const androidResult = await tracksFromAndroidInnerTube(videoId);
        if (androidResult && androidResult.tracks.length > 0) {
          title = androidResult.title;
          tracks = androidResult.tracks;
        }
      }

      // Static data is the final discovery fallback, never preferred to live URLs.
      if (tracks.length === 0) {
        const initialResult = tracksFromInitialResponse(videoId);
        if (initialResult?.tracks.length) {
          title = initialResult.title;
          tracks = initialResult.tracks;
        }
      }

      if (inferVideoId() !== videoId) return;

      const data: HakkutsuYouTubeSyncedData = {
        videoId,
        title,
        tracks,
      };

      document.dispatchEvent(
        new CustomEvent("hakkutsu:youtube-synced-tracks", {
          detail: data,
        })
      );
    }

    const discoveries = new Map<string, Promise<void>>();
    function publishCurrentTracks(): Promise<void> {
      const videoId = inferVideoId();
      if (!videoId) return Promise.resolve();
      const pending = discoveries.get(videoId);
      if (pending) return pending;
      const request = discoverTracks(videoId).finally(() => discoveries.delete(videoId));
      discoveries.set(videoId, request);
      return request;
    }

    document.addEventListener("hakkutsu:request-youtube-tracks", () => {
      void publishCurrentTracks();
    });

    document.addEventListener("hakkutsu:request-youtube-caption-content", async (event: Event) => {
      const detail = (event as CustomEvent).detail;
      if (typeof detail?.requestId !== "string" || typeof detail?.url !== "string") return;
      const videoId = inferVideoId();
      const controller = new AbortController();
      let timer: ReturnType<typeof setTimeout> | undefined;
      try {
        const url = new URL(detail.url, window.location.href);
        if (url.protocol !== "https:" || !["www.youtube.com", "m.youtube.com", "youtube.com"].includes(url.hostname) || url.pathname !== "/api/timedtext" ||
          !videoId || url.searchParams.get("v") !== videoId) throw new Error("Invalid caption request");
        timer = setTimeout(() => controller.abort(), 8000);
        const response = await fetch(url.toString(), { credentials: "include", signal: controller.signal });
        const text = response.ok ? await response.text() : "";
        if (inferVideoId() !== videoId) throw new Error("Video changed during subtitle request");
        document.dispatchEvent(new CustomEvent("hakkutsu:youtube-caption-content", {
          detail: { requestId: detail.requestId, text, error: response.ok ? undefined : `HTTP ${response.status}` },
        }));
      } catch (error) {
        document.dispatchEvent(new CustomEvent("hakkutsu:youtube-caption-content", {
          detail: { requestId: detail.requestId, error: error instanceof Error ? error.message : String(error) },
        }));
      } finally {
        if (timer !== undefined) clearTimeout(timer);
      }
    });

    document.addEventListener("hakkutsu:youtube-seek", (e: Event) => {
      const timeSec = (e as CustomEvent).detail?.timeSec;
      if (typeof timeSec === "number") {
        try {
          const player = document.querySelector<any>("#movie_player");
          if (player && typeof player.seekTo === "function") {
            player.seekTo(timeSec, true);
          }
        } catch (err) {
          console.warn("[Hakkutsu Bridge] YouTube seek error:", err);
        }
      }
    });

    window.addEventListener("yt-navigate-finish", () => {
      setTimeout(() => {
        void publishCurrentTracks();
      }, 600);
    });

    let lastDispatchedVideoId: string | undefined;
    let lastRuntimeSignature = "";
    setInterval(() => {
      const currentVideoId = inferVideoId();
      const player = document.querySelector<any>("#movie_player");
      const runtimeTracks = player?.getAudioTrack?.()?.captionTracks;
      const signature = Array.isArray(runtimeTracks) && player?.getVideoData?.()?.video_id === currentVideoId
        ? JSON.stringify(runtimeTracks.map((track: CaptionTrackDef) => [track.languageCode, track.url || track.baseUrl])) : "";
      if (currentVideoId && (currentVideoId !== lastDispatchedVideoId || signature !== lastRuntimeSignature)) {
        lastDispatchedVideoId = currentVideoId;
        lastRuntimeSignature = signature;
        void publishCurrentTracks();
      }
    }, 1000);

    setTimeout(() => {
      void publishCurrentTracks();
    }, 1000);
  }

  if (typeof window === "undefined") return;

  // Firefox MV2 ignores the manifest's MAIN world field. In that case this
  // entrypoint runs as an extension content script, so load the same bundled
  // bridge through a page script. Chromium MAIN-world execution takes the
  // direct branch and avoids duplicate injection.
  const extensionRuntime = (globalThis as any).browser?.runtime || (globalThis as any).chrome?.runtime;
  if (extensionRuntime?.id) {
    const scriptId = "hakkutsu-youtube-main-bridge";
    if (!document.getElementById(scriptId)) {
      const script = document.createElement("script");
      script.id = scriptId;
      script.src = extensionRuntime.getURL("content-scripts/youtube-bridge.js");
      script.addEventListener("load", () => script.remove(), { once: true });
      (document.head || document.documentElement).appendChild(script);
    }
    return;
  }

  bridgeMain();
}

