/**
 * YouTube Page Bridge — runs in YouTube's MAIN world.
 *
 * Adopts ASBPlayer's proven extraction techniques:
 * 1. Inspects #movie_player.getAudioTrack()?.captionTracks with runtime POT tokens.
 * 2. Fallbacks to YouTube's Android InnerTube API (/youtubei/v1/player) to bypass POT enforcement.
 * 3. Prepares srv3 timedtext URLs.
 * 4. Communicates with Hakkutsu's content script via CustomEvents.
 */

export interface HakkutsuYouTubeTrack {
  id: string;
  label: string;
  language: string;
  url: string;
  isAutoGenerated: boolean;
  kind?: string;
}

export interface HakkutsuYouTubeSyncedData {
  videoId: string;
  title: string;
  tracks: HakkutsuYouTubeTrack[];
  error?: string;
}

export function initYouTubePageBridge(): void {
  function bridgeMain() {
    if ((window as any).__HAKKUTSU_YT_BRIDGE_INITIALIZED__) return;
    (window as any).__HAKKUTSU_YT_BRIDGE_INITIALIZED__ = true;

    interface CaptionTrackDef {
      baseUrl?: string;
      url?: string;
      name?: { simpleText?: string; runs?: Array<{ text: string }> };
      displayName?: string;
      languageName?: string;
      languageCode: string;
      vssId?: string;
      kind?: string;
    }

    function pollCondition<T>(fn: () => T | null | undefined | false, timeoutMs: number = 5000, intervalMs: number = 200): Promise<T | null> {
      return new Promise((resolve) => {
        const startTime = Date.now();
        const check = () => {
          try {
            const result = fn();
            if (result) {
              resolve(result);
              return;
            }
          } catch {
            // ignore
          }

          if (Date.now() - startTime >= timeoutMs) {
            resolve(null);
          } else {
            setTimeout(check, intervalMs);
          }
        };
        check();
      });
    }

    const inferVideoId = (): string | undefined => {
      const pathname = window.location.pathname;
      if (pathname) {
        const pathVideoId = /\/(shorts|embed)\/([^/?&#]+)/.exec(pathname)?.[2];
        if (pathVideoId) return pathVideoId;
      }
      const params = new URLSearchParams(window.location.search);
      return params.get("v") ?? undefined;
    };

    const getTrackLabel = (track: CaptionTrackDef): string => {
      return (
        track.name?.simpleText ||
        track.name?.runs?.[0]?.text ||
        track.displayName ||
        track.languageName ||
        track.languageCode ||
        "Unknown Track"
      );
    };

    const prepareTimedTextUrl = (rawUrl: string): string => {
      try {
        const url = new URL(rawUrl, window.location.href);
        url.searchParams.set("fmt", "srv3");
        const ytcfg = (window as any).ytcfg;
        const clientName = ytcfg?.get?.("INNERTUBE_CLIENT_NAME") || "WEB";
        url.searchParams.set("c", clientName);
        return url.toString();
      } catch {
        return rawUrl;
      }
    };

    const normalizeTrack = (track: CaptionTrackDef): HakkutsuYouTubeTrack | null => {
      const timedTextUrl = track.url || track.baseUrl;
      const language = track.languageCode;
      if (!timedTextUrl || !language) return null;

      const url = prepareTimedTextUrl(timedTextUrl);
      const isAutoGenerated = track.kind === "asr" || (track.vssId ? track.vssId.startsWith("a.") : false);

      return {
        id: `${language}-${track.vssId || ""}-${isAutoGenerated ? "auto" : "std"}`,
        label: getTrackLabel(track),
        language,
        url,
        isAutoGenerated,
        kind: track.kind,
      };
    };

    async function tracksFromPlayerAudioTrack(videoId: string): Promise<{ title: string; tracks: HakkutsuYouTubeTrack[] } | null> {
      const result = await pollCondition(() => {
        const player = document.querySelector<any>("#movie_player");
        if (!player) return false;

        const playerVideoId = player.getVideoData?.()?.video_id;
        if (playerVideoId && playerVideoId !== videoId) return false;

        const tracks = player.getAudioTrack?.()?.captionTracks;
        if (Array.isArray(tracks) && tracks.length > 0) {
          const normalized = tracks
            .map(normalizeTrack)
            .filter((t): t is HakkutsuYouTubeTrack => t !== null);

          if (normalized.length > 0) {
            return {
              title: player.getVideoData?.()?.title || document.title,
              tracks: normalized,
            };
          }
        }
        return false;
      }, 4000);

      if (result) {
        return { title: result.title, tracks: result.tracks };
      }
      return null;
    }

    async function tracksFromAndroidInnerTube(videoId: string): Promise<{ title: string; tracks: HakkutsuYouTubeTrack[] } | null> {
      try {
        const ytcfg = (window as any).ytcfg;
        if (typeof ytcfg?.get !== "function") return null;

        const apiKey = ytcfg.get("INNERTUBE_API_KEY");
        if (!apiKey) return null;

        const response = await fetch(`https://${window.location.host}/youtubei/v1/player?key=${apiKey}`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            context: {
              client: {
                clientName: "ANDROID",
                clientVersion: "20.10.38",
                hl: ytcfg.get("HL") || "en",
              },
            },
            videoId,
          }),
        });

        if (response.status !== 200) return null;
        const payload = await response.json();
        const title = payload.videoDetails?.title || document.title;
        const captionTracks = payload?.captions?.playerCaptionsTracklistRenderer?.captionTracks;

        if (Array.isArray(captionTracks) && captionTracks.length > 0) {
          const tracks = captionTracks
            .map(normalizeTrack)
            .filter((t): t is HakkutsuYouTubeTrack => t !== null);
          return { title, tracks };
        }
      } catch (err) {
        console.warn("[Hakkutsu Bridge] Android InnerTube error:", err);
      }
      return null;
    }

    function tracksFromInitialResponse(): { title: string; tracks: HakkutsuYouTubeTrack[] } | null {
      try {
        const response = (window as any).ytInitialPlayerResponse;
        const captionTracks = response?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
        const title = response?.videoDetails?.title || document.title;

        if (Array.isArray(captionTracks) && captionTracks.length > 0) {
          const tracks = captionTracks
            .map(normalizeTrack)
            .filter((t): t is HakkutsuYouTubeTrack => t !== null);
          if (tracks.length > 0) {
            return { title, tracks };
          }
        }
      } catch {
        // ignore
      }
      return null;
    }

    async function publishCurrentTracks(): Promise<void> {
      const videoId = inferVideoId();
      if (!videoId) return;

      let title = document.title;
      let tracks: HakkutsuYouTubeTrack[] = [];

      // 1. Instant check from initial player response
      const initialResult = tracksFromInitialResponse();
      if (initialResult && initialResult.tracks.length > 0) {
        title = initialResult.title;
        tracks = initialResult.tracks;
      }

      // 2. Fetch InnerTube API in parallel (instant ~100ms response independent of CC button state)
      if (tracks.length === 0) {
        const androidResult = await tracksFromAndroidInnerTube(videoId);
        if (androidResult && androidResult.tracks.length > 0) {
          title = androidResult.title;
          tracks = androidResult.tracks;
        }
      }

      // 3. Fallback to player audio track
      if (tracks.length === 0) {
        const playerResult = await tracksFromPlayerAudioTrack(videoId);
        if (playerResult && playerResult.tracks.length > 0) {
          title = playerResult.title;
          tracks = playerResult.tracks;
        }
      }

      if (inferVideoId() !== videoId) return;

      const data: HakkutsuYouTubeSyncedData = {
        videoId,
        title,
        tracks,
      };

      document.dispatchEvent(
        new CustomEvent("hakkutsu:youtube-synced-tracks", {
          detail: data,
        })
      );
    }

    document.addEventListener("hakkutsu:request-youtube-tracks", () => {
      void publishCurrentTracks();
    });

    window.addEventListener("yt-navigate-finish", () => {
      setTimeout(() => {
        void publishCurrentTracks();
      }, 600);
    });

    let lastDispatchedVideoId: string | undefined;
    setInterval(() => {
      const currentVideoId = inferVideoId();
      if (currentVideoId && currentVideoId !== lastDispatchedVideoId) {
        lastDispatchedVideoId = currentVideoId;
        void publishCurrentTracks();
      }
    }, 1000);

    setTimeout(() => {
      void publishCurrentTracks();
    }, 1000);
  }

  // Inject into page MAIN world with Trusted Types support
  if (typeof document === "undefined") return;
  const BRIDGE_ID = "hakkutsu-youtube-main-bridge";
  if (document.getElementById(BRIDGE_ID)) return;

  const script = document.createElement("script");
  script.id = BRIDGE_ID;
  const code = `(${bridgeMain.toString()})();`;

  try {
    const trustedTypes = (window as any).trustedTypes;
    if (trustedTypes && typeof trustedTypes.createPolicy === "function") {
      let policy: any;
      try {
        policy = trustedTypes.createPolicy("hakkutsu-yt-policy", {
          createScript: (s: string) => s,
        });
      } catch {
        policy = trustedTypes.defaultPolicy;
      }
      if (policy?.createScript) {
        script.textContent = policy.createScript(code);
      } else {
        script.textContent = code;
      }
    } else {
      script.textContent = code;
    }
  } catch {
    script.textContent = code;
  }

  (document.head || document.documentElement).appendChild(script);
}

